-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dataflow_in_loop_lea is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    hcl_trainLabels_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    hcl_trainLabels_V_ce0 : OUT STD_LOGIC;
    hcl_trainLabels_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hcl_trainLabels_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    hcl_trainLabels_V_we0 : OUT STD_LOGIC;
    hcl_trainLabels_V_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    hcl_trainLabels_V_ce1 : OUT STD_LOGIC;
    hcl_trainLabels_V_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    hcl_trainLabels_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    hcl_trainLabels_V_we1 : OUT STD_LOGIC;
    p_0510_0 : IN STD_LOGIC_VECTOR (4 downto 0);
    hcl_in_train_V_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    hcl_in_train_V_ce0 : OUT STD_LOGIC;
    hcl_in_train_V_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    hcl_in_train_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    hcl_in_train_V_we0 : OUT STD_LOGIC;
    hcl_in_train_V_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    hcl_in_train_V_ce1 : OUT STD_LOGIC;
    hcl_in_train_V_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    hcl_in_train_V_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    hcl_in_train_V_we1 : OUT STD_LOGIC;
    compute1_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    compute1_V_ce0 : OUT STD_LOGIC;
    compute1_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    compute1_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    compute1_V_we0 : OUT STD_LOGIC;
    compute1_V_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    compute1_V_ce1 : OUT STD_LOGIC;
    compute1_V_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    compute1_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    compute1_V_we1 : OUT STD_LOGIC;
    hcl_rdv3_V_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    hcl_rdv3_V_ce0 : OUT STD_LOGIC;
    hcl_rdv3_V_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    hcl_rdv3_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    hcl_rdv3_V_we0 : OUT STD_LOGIC;
    hcl_rdv3_V_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    hcl_rdv3_V_ce1 : OUT STD_LOGIC;
    hcl_rdv3_V_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    hcl_rdv3_V_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    hcl_rdv3_V_we1 : OUT STD_LOGIC;
    prototype_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    prototype_V_ce0 : OUT STD_LOGIC;
    prototype_V_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    prototype_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    prototype_V_we0 : OUT STD_LOGIC;
    prototype_V_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    prototype_V_ce1 : OUT STD_LOGIC;
    prototype_V_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    prototype_V_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
    prototype_V_we1 : OUT STD_LOGIC;
    prototypeCounter_V_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    prototypeCounter_V_ce0 : OUT STD_LOGIC;
    prototypeCounter_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    prototypeCounter_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    prototypeCounter_V_we0 : OUT STD_LOGIC;
    prototypeCounter_V_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    prototypeCounter_V_ce1 : OUT STD_LOGIC;
    prototypeCounter_V_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    prototypeCounter_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    prototypeCounter_V_we1 : OUT STD_LOGIC;
    p_0510_0_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of dataflow_in_loop_lea is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal compute2_V_i_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal compute2_V_t_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal match_x4_proc_U0_ap_start : STD_LOGIC;
    signal match_x4_proc_U0_ap_done : STD_LOGIC;
    signal match_x4_proc_U0_ap_continue : STD_LOGIC;
    signal match_x4_proc_U0_ap_idle : STD_LOGIC;
    signal match_x4_proc_U0_ap_ready : STD_LOGIC;
    signal match_x4_proc_U0_hcl_trainLabels_V_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal match_x4_proc_U0_hcl_trainLabels_V_ce0 : STD_LOGIC;
    signal match_x4_proc_U0_compute2_V1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal match_x4_proc_U0_compute2_V1_ce0 : STD_LOGIC;
    signal match_x4_proc_U0_compute2_V1_we0 : STD_LOGIC;
    signal match_x4_proc_U0_compute2_V1_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal match_x4_proc_U0_hcl_in_train_V_address0 : STD_LOGIC_VECTOR (19 downto 0);
    signal match_x4_proc_U0_hcl_in_train_V_ce0 : STD_LOGIC;
    signal match_x4_proc_U0_match2_din : STD_LOGIC_VECTOR (63 downto 0);
    signal match_x4_proc_U0_match2_write : STD_LOGIC;
    signal match_x4_proc_U0_p_0510_0_out_din : STD_LOGIC_VECTOR (4 downto 0);
    signal match_x4_proc_U0_p_0510_0_out_write : STD_LOGIC;
    signal ap_channel_done_compute2_V : STD_LOGIC;
    signal match_x4_proc_U0_compute2_V1_full_n : STD_LOGIC;
    signal i2_proc_U0_ap_start : STD_LOGIC;
    signal i2_proc_U0_ap_done : STD_LOGIC;
    signal i2_proc_U0_ap_continue : STD_LOGIC;
    signal i2_proc_U0_ap_idle : STD_LOGIC;
    signal i2_proc_U0_ap_ready : STD_LOGIC;
    signal i2_proc_U0_compute2_V1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal i2_proc_U0_compute2_V1_ce0 : STD_LOGIC;
    signal i2_proc_U0_p_0510_0_read : STD_LOGIC;
    signal i2_proc_U0_compute1_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal i2_proc_U0_compute1_V_ce0 : STD_LOGIC;
    signal i2_proc_U0_compute1_V_we0 : STD_LOGIC;
    signal i2_proc_U0_compute1_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal i2_proc_U0_match2_read : STD_LOGIC;
    signal i2_proc_U0_hcl_rdv3_V_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal i2_proc_U0_hcl_rdv3_V_ce0 : STD_LOGIC;
    signal i2_proc_U0_prototype_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal i2_proc_U0_prototype_V_ce0 : STD_LOGIC;
    signal i2_proc_U0_prototype_V_we0 : STD_LOGIC_VECTOR (7 downto 0);
    signal i2_proc_U0_prototype_V_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal i2_proc_U0_prototypeCounter_V_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal i2_proc_U0_prototypeCounter_V_ce0 : STD_LOGIC;
    signal i2_proc_U0_prototypeCounter_V_we0 : STD_LOGIC;
    signal i2_proc_U0_prototypeCounter_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal compute2_V_i_full_n : STD_LOGIC;
    signal compute2_V_t_empty_n : STD_LOGIC;
    signal match2_channel_full_n : STD_LOGIC;
    signal match2_channel_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal match2_channel_empty_n : STD_LOGIC;
    signal p_0510_0_c_full_n : STD_LOGIC;
    signal p_0510_0_c_dout : STD_LOGIC_VECTOR (4 downto 0);
    signal p_0510_0_c_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_match_x4_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_match_x4_proc_U0_ap_ready : STD_LOGIC;
    signal match_x4_proc_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_i2_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_i2_proc_U0_ap_ready : STD_LOGIC;
    signal i2_proc_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal match_x4_proc_U0_start_full_n : STD_LOGIC;
    signal match_x4_proc_U0_start_write : STD_LOGIC;
    signal i2_proc_U0_start_full_n : STD_LOGIC;
    signal i2_proc_U0_start_write : STD_LOGIC;

    component match_x4_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        hcl_trainLabels_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        hcl_trainLabels_V_ce0 : OUT STD_LOGIC;
        hcl_trainLabels_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        compute2_V1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        compute2_V1_ce0 : OUT STD_LOGIC;
        compute2_V1_we0 : OUT STD_LOGIC;
        compute2_V1_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_0510_0 : IN STD_LOGIC_VECTOR (4 downto 0);
        hcl_in_train_V_address0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        hcl_in_train_V_ce0 : OUT STD_LOGIC;
        hcl_in_train_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        match2_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        match2_full_n : IN STD_LOGIC;
        match2_write : OUT STD_LOGIC;
        p_0510_0_out_din : OUT STD_LOGIC_VECTOR (4 downto 0);
        p_0510_0_out_full_n : IN STD_LOGIC;
        p_0510_0_out_write : OUT STD_LOGIC );
    end component;


    component i2_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        compute2_V1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        compute2_V1_ce0 : OUT STD_LOGIC;
        compute2_V1_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_0510_0_dout : IN STD_LOGIC_VECTOR (4 downto 0);
        p_0510_0_empty_n : IN STD_LOGIC;
        p_0510_0_read : OUT STD_LOGIC;
        compute1_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        compute1_V_ce0 : OUT STD_LOGIC;
        compute1_V_we0 : OUT STD_LOGIC;
        compute1_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        match2_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        match2_empty_n : IN STD_LOGIC;
        match2_read : OUT STD_LOGIC;
        hcl_rdv3_V_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        hcl_rdv3_V_ce0 : OUT STD_LOGIC;
        hcl_rdv3_V_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        prototype_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        prototype_V_ce0 : OUT STD_LOGIC;
        prototype_V_we0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        prototype_V_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        prototypeCounter_V_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        prototypeCounter_V_ce0 : OUT STD_LOGIC;
        prototypeCounter_V_we0 : OUT STD_LOGIC;
        prototypeCounter_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dataflow_in_loop_dEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component fifo_w64_d6238_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w5_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (4 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    compute2_V_U : component dataflow_in_loop_dEe
    generic map (
        DataWidth => 1,
        AddressRange => 26,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => match_x4_proc_U0_compute2_V1_address0,
        i_ce0 => match_x4_proc_U0_compute2_V1_ce0,
        i_we0 => match_x4_proc_U0_compute2_V1_we0,
        i_d0 => match_x4_proc_U0_compute2_V1_d0,
        i_q0 => compute2_V_i_q0,
        t_address0 => i2_proc_U0_compute2_V1_address0,
        t_ce0 => i2_proc_U0_compute2_V1_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv1_0,
        t_q0 => compute2_V_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => compute2_V_i_full_n,
        i_write => match_x4_proc_U0_ap_done,
        t_empty_n => compute2_V_t_empty_n,
        t_read => i2_proc_U0_ap_ready);

    match_x4_proc_U0 : component match_x4_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => match_x4_proc_U0_ap_start,
        ap_done => match_x4_proc_U0_ap_done,
        ap_continue => match_x4_proc_U0_ap_continue,
        ap_idle => match_x4_proc_U0_ap_idle,
        ap_ready => match_x4_proc_U0_ap_ready,
        hcl_trainLabels_V_address0 => match_x4_proc_U0_hcl_trainLabels_V_address0,
        hcl_trainLabels_V_ce0 => match_x4_proc_U0_hcl_trainLabels_V_ce0,
        hcl_trainLabels_V_q0 => hcl_trainLabels_V_q0,
        compute2_V1_address0 => match_x4_proc_U0_compute2_V1_address0,
        compute2_V1_ce0 => match_x4_proc_U0_compute2_V1_ce0,
        compute2_V1_we0 => match_x4_proc_U0_compute2_V1_we0,
        compute2_V1_d0 => match_x4_proc_U0_compute2_V1_d0,
        p_0510_0 => p_0510_0,
        hcl_in_train_V_address0 => match_x4_proc_U0_hcl_in_train_V_address0,
        hcl_in_train_V_ce0 => match_x4_proc_U0_hcl_in_train_V_ce0,
        hcl_in_train_V_q0 => hcl_in_train_V_q0,
        match2_din => match_x4_proc_U0_match2_din,
        match2_full_n => match2_channel_full_n,
        match2_write => match_x4_proc_U0_match2_write,
        p_0510_0_out_din => match_x4_proc_U0_p_0510_0_out_din,
        p_0510_0_out_full_n => p_0510_0_c_full_n,
        p_0510_0_out_write => match_x4_proc_U0_p_0510_0_out_write);

    i2_proc_U0 : component i2_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => i2_proc_U0_ap_start,
        ap_done => i2_proc_U0_ap_done,
        ap_continue => i2_proc_U0_ap_continue,
        ap_idle => i2_proc_U0_ap_idle,
        ap_ready => i2_proc_U0_ap_ready,
        compute2_V1_address0 => i2_proc_U0_compute2_V1_address0,
        compute2_V1_ce0 => i2_proc_U0_compute2_V1_ce0,
        compute2_V1_q0 => compute2_V_t_q0,
        p_0510_0_dout => p_0510_0_c_dout,
        p_0510_0_empty_n => p_0510_0_c_empty_n,
        p_0510_0_read => i2_proc_U0_p_0510_0_read,
        compute1_V_address0 => i2_proc_U0_compute1_V_address0,
        compute1_V_ce0 => i2_proc_U0_compute1_V_ce0,
        compute1_V_we0 => i2_proc_U0_compute1_V_we0,
        compute1_V_d0 => i2_proc_U0_compute1_V_d0,
        match2_dout => match2_channel_dout,
        match2_empty_n => match2_channel_empty_n,
        match2_read => i2_proc_U0_match2_read,
        hcl_rdv3_V_address0 => i2_proc_U0_hcl_rdv3_V_address0,
        hcl_rdv3_V_ce0 => i2_proc_U0_hcl_rdv3_V_ce0,
        hcl_rdv3_V_q0 => hcl_rdv3_V_q0,
        prototype_V_address0 => i2_proc_U0_prototype_V_address0,
        prototype_V_ce0 => i2_proc_U0_prototype_V_ce0,
        prototype_V_we0 => i2_proc_U0_prototype_V_we0,
        prototype_V_d0 => i2_proc_U0_prototype_V_d0,
        prototypeCounter_V_address0 => i2_proc_U0_prototypeCounter_V_address0,
        prototypeCounter_V_ce0 => i2_proc_U0_prototypeCounter_V_ce0,
        prototypeCounter_V_we0 => i2_proc_U0_prototypeCounter_V_we0,
        prototypeCounter_V_d0 => i2_proc_U0_prototypeCounter_V_d0);

    match2_channel_U : component fifo_w64_d6238_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => match_x4_proc_U0_match2_din,
        if_full_n => match2_channel_full_n,
        if_write => match_x4_proc_U0_match2_write,
        if_dout => match2_channel_dout,
        if_empty_n => match2_channel_empty_n,
        if_read => i2_proc_U0_match2_read);

    p_0510_0_c_U : component fifo_w5_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => match_x4_proc_U0_p_0510_0_out_din,
        if_full_n => p_0510_0_c_full_n,
        if_write => match_x4_proc_U0_p_0510_0_out_write,
        if_dout => p_0510_0_c_dout,
        if_empty_n => p_0510_0_c_empty_n,
        if_read => i2_proc_U0_p_0510_0_read);





    ap_sync_reg_i2_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_i2_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_i2_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_i2_proc_U0_ap_ready <= ap_sync_i2_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_match_x4_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_match_x4_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_match_x4_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_match_x4_proc_U0_ap_ready <= ap_sync_match_x4_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    i2_proc_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((i2_proc_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                i2_proc_U0_ap_ready_count <= std_logic_vector(unsigned(i2_proc_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (i2_proc_U0_ap_ready = ap_const_logic_1))) then 
                i2_proc_U0_ap_ready_count <= std_logic_vector(unsigned(i2_proc_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    match_x4_proc_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((match_x4_proc_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                match_x4_proc_U0_ap_ready_count <= std_logic_vector(unsigned(match_x4_proc_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (match_x4_proc_U0_ap_ready = ap_const_logic_1))) then 
                match_x4_proc_U0_ap_ready_count <= std_logic_vector(unsigned(match_x4_proc_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;
    ap_channel_done_compute2_V <= match_x4_proc_U0_ap_done;
    ap_done <= i2_proc_U0_ap_done;
    ap_idle <= (match_x4_proc_U0_ap_idle and i2_proc_U0_ap_idle and (compute2_V_t_empty_n xor ap_const_logic_1));
    ap_ready <= ap_sync_ready;
    ap_sync_continue <= ap_continue;
    ap_sync_done <= i2_proc_U0_ap_done;
    ap_sync_i2_proc_U0_ap_ready <= (i2_proc_U0_ap_ready or ap_sync_reg_i2_proc_U0_ap_ready);
    ap_sync_match_x4_proc_U0_ap_ready <= (match_x4_proc_U0_ap_ready or ap_sync_reg_match_x4_proc_U0_ap_ready);
    ap_sync_ready <= (ap_sync_match_x4_proc_U0_ap_ready and ap_sync_i2_proc_U0_ap_ready);
    compute1_V_address0 <= i2_proc_U0_compute1_V_address0;
    compute1_V_address1 <= ap_const_lv5_0;
    compute1_V_ce0 <= i2_proc_U0_compute1_V_ce0;
    compute1_V_ce1 <= ap_const_logic_0;
    compute1_V_d0 <= i2_proc_U0_compute1_V_d0;
    compute1_V_d1 <= ap_const_lv32_0;
    compute1_V_we0 <= i2_proc_U0_compute1_V_we0;
    compute1_V_we1 <= ap_const_logic_0;
    hcl_in_train_V_address0 <= match_x4_proc_U0_hcl_in_train_V_address0;
    hcl_in_train_V_address1 <= ap_const_lv20_0;
    hcl_in_train_V_ce0 <= match_x4_proc_U0_hcl_in_train_V_ce0;
    hcl_in_train_V_ce1 <= ap_const_logic_0;
    hcl_in_train_V_d0 <= ap_const_lv64_0;
    hcl_in_train_V_d1 <= ap_const_lv64_0;
    hcl_in_train_V_we0 <= ap_const_logic_0;
    hcl_in_train_V_we1 <= ap_const_logic_0;
    hcl_rdv3_V_address0 <= i2_proc_U0_hcl_rdv3_V_address0;
    hcl_rdv3_V_address1 <= ap_const_lv18_0;
    hcl_rdv3_V_ce0 <= i2_proc_U0_hcl_rdv3_V_ce0;
    hcl_rdv3_V_ce1 <= ap_const_logic_0;
    hcl_rdv3_V_d0 <= ap_const_lv64_0;
    hcl_rdv3_V_d1 <= ap_const_lv64_0;
    hcl_rdv3_V_we0 <= ap_const_logic_0;
    hcl_rdv3_V_we1 <= ap_const_logic_0;
    hcl_trainLabels_V_address0 <= match_x4_proc_U0_hcl_trainLabels_V_address0;
    hcl_trainLabels_V_address1 <= ap_const_lv13_0;
    hcl_trainLabels_V_ce0 <= match_x4_proc_U0_hcl_trainLabels_V_ce0;
    hcl_trainLabels_V_ce1 <= ap_const_logic_0;
    hcl_trainLabels_V_d0 <= ap_const_lv32_0;
    hcl_trainLabels_V_d1 <= ap_const_lv32_0;
    hcl_trainLabels_V_we0 <= ap_const_logic_0;
    hcl_trainLabels_V_we1 <= ap_const_logic_0;
    i2_proc_U0_ap_continue <= ap_continue;
    i2_proc_U0_ap_start <= ((ap_sync_reg_i2_proc_U0_ap_ready xor ap_const_logic_1) and compute2_V_t_empty_n and ap_start);
    i2_proc_U0_start_full_n <= ap_const_logic_1;
    i2_proc_U0_start_write <= ap_const_logic_0;
    match_x4_proc_U0_ap_continue <= compute2_V_i_full_n;
    match_x4_proc_U0_ap_start <= ((ap_sync_reg_match_x4_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    match_x4_proc_U0_compute2_V1_full_n <= compute2_V_i_full_n;
    match_x4_proc_U0_start_full_n <= ap_const_logic_1;
    match_x4_proc_U0_start_write <= ap_const_logic_0;
    prototypeCounter_V_address0 <= i2_proc_U0_prototypeCounter_V_address0;
    prototypeCounter_V_address1 <= ap_const_lv18_0;
    prototypeCounter_V_ce0 <= i2_proc_U0_prototypeCounter_V_ce0;
    prototypeCounter_V_ce1 <= ap_const_logic_0;
    prototypeCounter_V_d0 <= i2_proc_U0_prototypeCounter_V_d0;
    prototypeCounter_V_d1 <= ap_const_lv32_0;
    prototypeCounter_V_we0 <= i2_proc_U0_prototypeCounter_V_we0;
    prototypeCounter_V_we1 <= ap_const_logic_0;
    prototype_V_address0 <= i2_proc_U0_prototype_V_address0;
    prototype_V_address1 <= ap_const_lv12_0;
    prototype_V_ce0 <= i2_proc_U0_prototype_V_ce0;
    prototype_V_ce1 <= ap_const_logic_0;
    prototype_V_d0 <= i2_proc_U0_prototype_V_d0;
    prototype_V_d1 <= ap_const_lv64_0;
    prototype_V_we0 <= i2_proc_U0_prototype_V_we0(0);
    prototype_V_we1 <= ap_const_logic_0;
end behav;
