// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dataflow_in_loop_lea.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dataflow_in_loop_lea::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<13> dataflow_in_loop_lea::ap_const_lv13_0 = "0000000000000";
const sc_logic dataflow_in_loop_lea::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<32> dataflow_in_loop_lea::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<20> dataflow_in_loop_lea::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<64> dataflow_in_loop_lea::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<5> dataflow_in_loop_lea::ap_const_lv5_0 = "00000";
const sc_lv<18> dataflow_in_loop_lea::ap_const_lv18_0 = "000000000000000000";
const sc_lv<12> dataflow_in_loop_lea::ap_const_lv12_0 = "000000000000";
const sc_lv<1> dataflow_in_loop_lea::ap_const_lv1_0 = "0";
const sc_lv<2> dataflow_in_loop_lea::ap_const_lv2_0 = "00";
const sc_lv<2> dataflow_in_loop_lea::ap_const_lv2_1 = "1";
const bool dataflow_in_loop_lea::ap_const_boolean_1 = true;

dataflow_in_loop_lea::dataflow_in_loop_lea(sc_module_name name) : sc_module(name), mVcdFile(0) {
    compute2_V_U = new dataflow_in_loop_dEe("compute2_V_U");
    compute2_V_U->clk(ap_clk);
    compute2_V_U->reset(ap_rst);
    compute2_V_U->i_address0(match_x4_proc_U0_compute2_V1_address0);
    compute2_V_U->i_ce0(match_x4_proc_U0_compute2_V1_ce0);
    compute2_V_U->i_we0(match_x4_proc_U0_compute2_V1_we0);
    compute2_V_U->i_d0(match_x4_proc_U0_compute2_V1_d0);
    compute2_V_U->i_q0(compute2_V_i_q0);
    compute2_V_U->t_address0(i2_proc_U0_compute2_V1_address0);
    compute2_V_U->t_ce0(i2_proc_U0_compute2_V1_ce0);
    compute2_V_U->t_we0(ap_var_for_const0);
    compute2_V_U->t_d0(ap_var_for_const1);
    compute2_V_U->t_q0(compute2_V_t_q0);
    compute2_V_U->i_ce(ap_var_for_const2);
    compute2_V_U->t_ce(ap_var_for_const2);
    compute2_V_U->i_full_n(compute2_V_i_full_n);
    compute2_V_U->i_write(match_x4_proc_U0_ap_done);
    compute2_V_U->t_empty_n(compute2_V_t_empty_n);
    compute2_V_U->t_read(i2_proc_U0_ap_ready);
    match_x4_proc_U0 = new match_x4_proc("match_x4_proc_U0");
    match_x4_proc_U0->ap_clk(ap_clk);
    match_x4_proc_U0->ap_rst(ap_rst);
    match_x4_proc_U0->ap_start(match_x4_proc_U0_ap_start);
    match_x4_proc_U0->ap_done(match_x4_proc_U0_ap_done);
    match_x4_proc_U0->ap_continue(match_x4_proc_U0_ap_continue);
    match_x4_proc_U0->ap_idle(match_x4_proc_U0_ap_idle);
    match_x4_proc_U0->ap_ready(match_x4_proc_U0_ap_ready);
    match_x4_proc_U0->hcl_trainLabels_V_address0(match_x4_proc_U0_hcl_trainLabels_V_address0);
    match_x4_proc_U0->hcl_trainLabels_V_ce0(match_x4_proc_U0_hcl_trainLabels_V_ce0);
    match_x4_proc_U0->hcl_trainLabels_V_q0(hcl_trainLabels_V_q0);
    match_x4_proc_U0->compute2_V1_address0(match_x4_proc_U0_compute2_V1_address0);
    match_x4_proc_U0->compute2_V1_ce0(match_x4_proc_U0_compute2_V1_ce0);
    match_x4_proc_U0->compute2_V1_we0(match_x4_proc_U0_compute2_V1_we0);
    match_x4_proc_U0->compute2_V1_d0(match_x4_proc_U0_compute2_V1_d0);
    match_x4_proc_U0->p_0510_0(p_0510_0);
    match_x4_proc_U0->hcl_in_train_V_address0(match_x4_proc_U0_hcl_in_train_V_address0);
    match_x4_proc_U0->hcl_in_train_V_ce0(match_x4_proc_U0_hcl_in_train_V_ce0);
    match_x4_proc_U0->hcl_in_train_V_q0(hcl_in_train_V_q0);
    match_x4_proc_U0->match2_din(match_x4_proc_U0_match2_din);
    match_x4_proc_U0->match2_full_n(match2_channel_full_n);
    match_x4_proc_U0->match2_write(match_x4_proc_U0_match2_write);
    match_x4_proc_U0->p_0510_0_out_din(match_x4_proc_U0_p_0510_0_out_din);
    match_x4_proc_U0->p_0510_0_out_full_n(p_0510_0_c_full_n);
    match_x4_proc_U0->p_0510_0_out_write(match_x4_proc_U0_p_0510_0_out_write);
    i2_proc_U0 = new i2_proc("i2_proc_U0");
    i2_proc_U0->ap_clk(ap_clk);
    i2_proc_U0->ap_rst(ap_rst);
    i2_proc_U0->ap_start(i2_proc_U0_ap_start);
    i2_proc_U0->ap_done(i2_proc_U0_ap_done);
    i2_proc_U0->ap_continue(i2_proc_U0_ap_continue);
    i2_proc_U0->ap_idle(i2_proc_U0_ap_idle);
    i2_proc_U0->ap_ready(i2_proc_U0_ap_ready);
    i2_proc_U0->compute2_V1_address0(i2_proc_U0_compute2_V1_address0);
    i2_proc_U0->compute2_V1_ce0(i2_proc_U0_compute2_V1_ce0);
    i2_proc_U0->compute2_V1_q0(compute2_V_t_q0);
    i2_proc_U0->p_0510_0_dout(p_0510_0_c_dout);
    i2_proc_U0->p_0510_0_empty_n(p_0510_0_c_empty_n);
    i2_proc_U0->p_0510_0_read(i2_proc_U0_p_0510_0_read);
    i2_proc_U0->compute1_V_address0(i2_proc_U0_compute1_V_address0);
    i2_proc_U0->compute1_V_ce0(i2_proc_U0_compute1_V_ce0);
    i2_proc_U0->compute1_V_we0(i2_proc_U0_compute1_V_we0);
    i2_proc_U0->compute1_V_d0(i2_proc_U0_compute1_V_d0);
    i2_proc_U0->match2_dout(match2_channel_dout);
    i2_proc_U0->match2_empty_n(match2_channel_empty_n);
    i2_proc_U0->match2_read(i2_proc_U0_match2_read);
    i2_proc_U0->hcl_rdv3_V_address0(i2_proc_U0_hcl_rdv3_V_address0);
    i2_proc_U0->hcl_rdv3_V_ce0(i2_proc_U0_hcl_rdv3_V_ce0);
    i2_proc_U0->hcl_rdv3_V_q0(hcl_rdv3_V_q0);
    i2_proc_U0->prototype_V_address0(i2_proc_U0_prototype_V_address0);
    i2_proc_U0->prototype_V_ce0(i2_proc_U0_prototype_V_ce0);
    i2_proc_U0->prototype_V_we0(i2_proc_U0_prototype_V_we0);
    i2_proc_U0->prototype_V_d0(i2_proc_U0_prototype_V_d0);
    i2_proc_U0->prototypeCounter_V_address0(i2_proc_U0_prototypeCounter_V_address0);
    i2_proc_U0->prototypeCounter_V_ce0(i2_proc_U0_prototypeCounter_V_ce0);
    i2_proc_U0->prototypeCounter_V_we0(i2_proc_U0_prototypeCounter_V_we0);
    i2_proc_U0->prototypeCounter_V_d0(i2_proc_U0_prototypeCounter_V_d0);
    match2_channel_U = new fifo_w64_d6238_A("match2_channel_U");
    match2_channel_U->clk(ap_clk);
    match2_channel_U->reset(ap_rst);
    match2_channel_U->if_read_ce(ap_var_for_const2);
    match2_channel_U->if_write_ce(ap_var_for_const2);
    match2_channel_U->if_din(match_x4_proc_U0_match2_din);
    match2_channel_U->if_full_n(match2_channel_full_n);
    match2_channel_U->if_write(match_x4_proc_U0_match2_write);
    match2_channel_U->if_dout(match2_channel_dout);
    match2_channel_U->if_empty_n(match2_channel_empty_n);
    match2_channel_U->if_read(i2_proc_U0_match2_read);
    p_0510_0_c_U = new fifo_w5_d2_A("p_0510_0_c_U");
    p_0510_0_c_U->clk(ap_clk);
    p_0510_0_c_U->reset(ap_rst);
    p_0510_0_c_U->if_read_ce(ap_var_for_const2);
    p_0510_0_c_U->if_write_ce(ap_var_for_const2);
    p_0510_0_c_U->if_din(match_x4_proc_U0_p_0510_0_out_din);
    p_0510_0_c_U->if_full_n(p_0510_0_c_full_n);
    p_0510_0_c_U->if_write(match_x4_proc_U0_p_0510_0_out_write);
    p_0510_0_c_U->if_dout(p_0510_0_c_dout);
    p_0510_0_c_U->if_empty_n(p_0510_0_c_empty_n);
    p_0510_0_c_U->if_read(i2_proc_U0_p_0510_0_read);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_channel_done_compute2_V);
    sensitive << ( match_x4_proc_U0_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( i2_proc_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( match_x4_proc_U0_ap_idle );
    sensitive << ( i2_proc_U0_ap_idle );
    sensitive << ( compute2_V_t_empty_n );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_sync_continue);
    sensitive << ( ap_continue );

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( i2_proc_U0_ap_done );

    SC_METHOD(thread_ap_sync_i2_proc_U0_ap_ready);
    sensitive << ( i2_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_i2_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_match_x4_proc_U0_ap_ready);
    sensitive << ( match_x4_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_match_x4_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_match_x4_proc_U0_ap_ready );
    sensitive << ( ap_sync_i2_proc_U0_ap_ready );

    SC_METHOD(thread_compute1_V_address0);
    sensitive << ( i2_proc_U0_compute1_V_address0 );

    SC_METHOD(thread_compute1_V_address1);

    SC_METHOD(thread_compute1_V_ce0);
    sensitive << ( i2_proc_U0_compute1_V_ce0 );

    SC_METHOD(thread_compute1_V_ce1);

    SC_METHOD(thread_compute1_V_d0);
    sensitive << ( i2_proc_U0_compute1_V_d0 );

    SC_METHOD(thread_compute1_V_d1);

    SC_METHOD(thread_compute1_V_we0);
    sensitive << ( i2_proc_U0_compute1_V_we0 );

    SC_METHOD(thread_compute1_V_we1);

    SC_METHOD(thread_hcl_in_train_V_address0);
    sensitive << ( match_x4_proc_U0_hcl_in_train_V_address0 );

    SC_METHOD(thread_hcl_in_train_V_address1);

    SC_METHOD(thread_hcl_in_train_V_ce0);
    sensitive << ( match_x4_proc_U0_hcl_in_train_V_ce0 );

    SC_METHOD(thread_hcl_in_train_V_ce1);

    SC_METHOD(thread_hcl_in_train_V_d0);

    SC_METHOD(thread_hcl_in_train_V_d1);

    SC_METHOD(thread_hcl_in_train_V_we0);

    SC_METHOD(thread_hcl_in_train_V_we1);

    SC_METHOD(thread_hcl_rdv3_V_address0);
    sensitive << ( i2_proc_U0_hcl_rdv3_V_address0 );

    SC_METHOD(thread_hcl_rdv3_V_address1);

    SC_METHOD(thread_hcl_rdv3_V_ce0);
    sensitive << ( i2_proc_U0_hcl_rdv3_V_ce0 );

    SC_METHOD(thread_hcl_rdv3_V_ce1);

    SC_METHOD(thread_hcl_rdv3_V_d0);

    SC_METHOD(thread_hcl_rdv3_V_d1);

    SC_METHOD(thread_hcl_rdv3_V_we0);

    SC_METHOD(thread_hcl_rdv3_V_we1);

    SC_METHOD(thread_hcl_trainLabels_V_address0);
    sensitive << ( match_x4_proc_U0_hcl_trainLabels_V_address0 );

    SC_METHOD(thread_hcl_trainLabels_V_address1);

    SC_METHOD(thread_hcl_trainLabels_V_ce0);
    sensitive << ( match_x4_proc_U0_hcl_trainLabels_V_ce0 );

    SC_METHOD(thread_hcl_trainLabels_V_ce1);

    SC_METHOD(thread_hcl_trainLabels_V_d0);

    SC_METHOD(thread_hcl_trainLabels_V_d1);

    SC_METHOD(thread_hcl_trainLabels_V_we0);

    SC_METHOD(thread_hcl_trainLabels_V_we1);

    SC_METHOD(thread_i2_proc_U0_ap_continue);
    sensitive << ( ap_continue );

    SC_METHOD(thread_i2_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( compute2_V_t_empty_n );
    sensitive << ( ap_sync_reg_i2_proc_U0_ap_ready );

    SC_METHOD(thread_i2_proc_U0_start_full_n);

    SC_METHOD(thread_i2_proc_U0_start_write);

    SC_METHOD(thread_match_x4_proc_U0_ap_continue);
    sensitive << ( compute2_V_i_full_n );

    SC_METHOD(thread_match_x4_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_match_x4_proc_U0_ap_ready );

    SC_METHOD(thread_match_x4_proc_U0_compute2_V1_full_n);
    sensitive << ( compute2_V_i_full_n );

    SC_METHOD(thread_match_x4_proc_U0_start_full_n);

    SC_METHOD(thread_match_x4_proc_U0_start_write);

    SC_METHOD(thread_prototypeCounter_V_address0);
    sensitive << ( i2_proc_U0_prototypeCounter_V_address0 );

    SC_METHOD(thread_prototypeCounter_V_address1);

    SC_METHOD(thread_prototypeCounter_V_ce0);
    sensitive << ( i2_proc_U0_prototypeCounter_V_ce0 );

    SC_METHOD(thread_prototypeCounter_V_ce1);

    SC_METHOD(thread_prototypeCounter_V_d0);
    sensitive << ( i2_proc_U0_prototypeCounter_V_d0 );

    SC_METHOD(thread_prototypeCounter_V_d1);

    SC_METHOD(thread_prototypeCounter_V_we0);
    sensitive << ( i2_proc_U0_prototypeCounter_V_we0 );

    SC_METHOD(thread_prototypeCounter_V_we1);

    SC_METHOD(thread_prototype_V_address0);
    sensitive << ( i2_proc_U0_prototype_V_address0 );

    SC_METHOD(thread_prototype_V_address1);

    SC_METHOD(thread_prototype_V_ce0);
    sensitive << ( i2_proc_U0_prototype_V_ce0 );

    SC_METHOD(thread_prototype_V_ce1);

    SC_METHOD(thread_prototype_V_d0);
    sensitive << ( i2_proc_U0_prototype_V_d0 );

    SC_METHOD(thread_prototype_V_d1);

    SC_METHOD(thread_prototype_V_we0);
    sensitive << ( i2_proc_U0_prototype_V_we0 );

    SC_METHOD(thread_prototype_V_we1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_sync_reg_match_x4_proc_U0_ap_ready = SC_LOGIC_0;
    match_x4_proc_U0_ap_ready_count = "00";
    ap_sync_reg_i2_proc_U0_ap_ready = SC_LOGIC_0;
    i2_proc_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dataflow_in_loop_lea_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, hcl_trainLabels_V_address0, "(port)hcl_trainLabels_V_address0");
    sc_trace(mVcdFile, hcl_trainLabels_V_ce0, "(port)hcl_trainLabels_V_ce0");
    sc_trace(mVcdFile, hcl_trainLabels_V_d0, "(port)hcl_trainLabels_V_d0");
    sc_trace(mVcdFile, hcl_trainLabels_V_q0, "(port)hcl_trainLabels_V_q0");
    sc_trace(mVcdFile, hcl_trainLabels_V_we0, "(port)hcl_trainLabels_V_we0");
    sc_trace(mVcdFile, hcl_trainLabels_V_address1, "(port)hcl_trainLabels_V_address1");
    sc_trace(mVcdFile, hcl_trainLabels_V_ce1, "(port)hcl_trainLabels_V_ce1");
    sc_trace(mVcdFile, hcl_trainLabels_V_d1, "(port)hcl_trainLabels_V_d1");
    sc_trace(mVcdFile, hcl_trainLabels_V_q1, "(port)hcl_trainLabels_V_q1");
    sc_trace(mVcdFile, hcl_trainLabels_V_we1, "(port)hcl_trainLabels_V_we1");
    sc_trace(mVcdFile, p_0510_0, "(port)p_0510_0");
    sc_trace(mVcdFile, hcl_in_train_V_address0, "(port)hcl_in_train_V_address0");
    sc_trace(mVcdFile, hcl_in_train_V_ce0, "(port)hcl_in_train_V_ce0");
    sc_trace(mVcdFile, hcl_in_train_V_d0, "(port)hcl_in_train_V_d0");
    sc_trace(mVcdFile, hcl_in_train_V_q0, "(port)hcl_in_train_V_q0");
    sc_trace(mVcdFile, hcl_in_train_V_we0, "(port)hcl_in_train_V_we0");
    sc_trace(mVcdFile, hcl_in_train_V_address1, "(port)hcl_in_train_V_address1");
    sc_trace(mVcdFile, hcl_in_train_V_ce1, "(port)hcl_in_train_V_ce1");
    sc_trace(mVcdFile, hcl_in_train_V_d1, "(port)hcl_in_train_V_d1");
    sc_trace(mVcdFile, hcl_in_train_V_q1, "(port)hcl_in_train_V_q1");
    sc_trace(mVcdFile, hcl_in_train_V_we1, "(port)hcl_in_train_V_we1");
    sc_trace(mVcdFile, compute1_V_address0, "(port)compute1_V_address0");
    sc_trace(mVcdFile, compute1_V_ce0, "(port)compute1_V_ce0");
    sc_trace(mVcdFile, compute1_V_d0, "(port)compute1_V_d0");
    sc_trace(mVcdFile, compute1_V_q0, "(port)compute1_V_q0");
    sc_trace(mVcdFile, compute1_V_we0, "(port)compute1_V_we0");
    sc_trace(mVcdFile, compute1_V_address1, "(port)compute1_V_address1");
    sc_trace(mVcdFile, compute1_V_ce1, "(port)compute1_V_ce1");
    sc_trace(mVcdFile, compute1_V_d1, "(port)compute1_V_d1");
    sc_trace(mVcdFile, compute1_V_q1, "(port)compute1_V_q1");
    sc_trace(mVcdFile, compute1_V_we1, "(port)compute1_V_we1");
    sc_trace(mVcdFile, hcl_rdv3_V_address0, "(port)hcl_rdv3_V_address0");
    sc_trace(mVcdFile, hcl_rdv3_V_ce0, "(port)hcl_rdv3_V_ce0");
    sc_trace(mVcdFile, hcl_rdv3_V_d0, "(port)hcl_rdv3_V_d0");
    sc_trace(mVcdFile, hcl_rdv3_V_q0, "(port)hcl_rdv3_V_q0");
    sc_trace(mVcdFile, hcl_rdv3_V_we0, "(port)hcl_rdv3_V_we0");
    sc_trace(mVcdFile, hcl_rdv3_V_address1, "(port)hcl_rdv3_V_address1");
    sc_trace(mVcdFile, hcl_rdv3_V_ce1, "(port)hcl_rdv3_V_ce1");
    sc_trace(mVcdFile, hcl_rdv3_V_d1, "(port)hcl_rdv3_V_d1");
    sc_trace(mVcdFile, hcl_rdv3_V_q1, "(port)hcl_rdv3_V_q1");
    sc_trace(mVcdFile, hcl_rdv3_V_we1, "(port)hcl_rdv3_V_we1");
    sc_trace(mVcdFile, prototype_V_address0, "(port)prototype_V_address0");
    sc_trace(mVcdFile, prototype_V_ce0, "(port)prototype_V_ce0");
    sc_trace(mVcdFile, prototype_V_d0, "(port)prototype_V_d0");
    sc_trace(mVcdFile, prototype_V_q0, "(port)prototype_V_q0");
    sc_trace(mVcdFile, prototype_V_we0, "(port)prototype_V_we0");
    sc_trace(mVcdFile, prototype_V_address1, "(port)prototype_V_address1");
    sc_trace(mVcdFile, prototype_V_ce1, "(port)prototype_V_ce1");
    sc_trace(mVcdFile, prototype_V_d1, "(port)prototype_V_d1");
    sc_trace(mVcdFile, prototype_V_q1, "(port)prototype_V_q1");
    sc_trace(mVcdFile, prototype_V_we1, "(port)prototype_V_we1");
    sc_trace(mVcdFile, prototypeCounter_V_address0, "(port)prototypeCounter_V_address0");
    sc_trace(mVcdFile, prototypeCounter_V_ce0, "(port)prototypeCounter_V_ce0");
    sc_trace(mVcdFile, prototypeCounter_V_d0, "(port)prototypeCounter_V_d0");
    sc_trace(mVcdFile, prototypeCounter_V_q0, "(port)prototypeCounter_V_q0");
    sc_trace(mVcdFile, prototypeCounter_V_we0, "(port)prototypeCounter_V_we0");
    sc_trace(mVcdFile, prototypeCounter_V_address1, "(port)prototypeCounter_V_address1");
    sc_trace(mVcdFile, prototypeCounter_V_ce1, "(port)prototypeCounter_V_ce1");
    sc_trace(mVcdFile, prototypeCounter_V_d1, "(port)prototypeCounter_V_d1");
    sc_trace(mVcdFile, prototypeCounter_V_q1, "(port)prototypeCounter_V_q1");
    sc_trace(mVcdFile, prototypeCounter_V_we1, "(port)prototypeCounter_V_we1");
    sc_trace(mVcdFile, p_0510_0_ap_vld, "(port)p_0510_0_ap_vld");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, compute2_V_i_q0, "compute2_V_i_q0");
    sc_trace(mVcdFile, compute2_V_t_q0, "compute2_V_t_q0");
    sc_trace(mVcdFile, match_x4_proc_U0_ap_start, "match_x4_proc_U0_ap_start");
    sc_trace(mVcdFile, match_x4_proc_U0_ap_done, "match_x4_proc_U0_ap_done");
    sc_trace(mVcdFile, match_x4_proc_U0_ap_continue, "match_x4_proc_U0_ap_continue");
    sc_trace(mVcdFile, match_x4_proc_U0_ap_idle, "match_x4_proc_U0_ap_idle");
    sc_trace(mVcdFile, match_x4_proc_U0_ap_ready, "match_x4_proc_U0_ap_ready");
    sc_trace(mVcdFile, match_x4_proc_U0_hcl_trainLabels_V_address0, "match_x4_proc_U0_hcl_trainLabels_V_address0");
    sc_trace(mVcdFile, match_x4_proc_U0_hcl_trainLabels_V_ce0, "match_x4_proc_U0_hcl_trainLabels_V_ce0");
    sc_trace(mVcdFile, match_x4_proc_U0_compute2_V1_address0, "match_x4_proc_U0_compute2_V1_address0");
    sc_trace(mVcdFile, match_x4_proc_U0_compute2_V1_ce0, "match_x4_proc_U0_compute2_V1_ce0");
    sc_trace(mVcdFile, match_x4_proc_U0_compute2_V1_we0, "match_x4_proc_U0_compute2_V1_we0");
    sc_trace(mVcdFile, match_x4_proc_U0_compute2_V1_d0, "match_x4_proc_U0_compute2_V1_d0");
    sc_trace(mVcdFile, match_x4_proc_U0_hcl_in_train_V_address0, "match_x4_proc_U0_hcl_in_train_V_address0");
    sc_trace(mVcdFile, match_x4_proc_U0_hcl_in_train_V_ce0, "match_x4_proc_U0_hcl_in_train_V_ce0");
    sc_trace(mVcdFile, match_x4_proc_U0_match2_din, "match_x4_proc_U0_match2_din");
    sc_trace(mVcdFile, match_x4_proc_U0_match2_write, "match_x4_proc_U0_match2_write");
    sc_trace(mVcdFile, match_x4_proc_U0_p_0510_0_out_din, "match_x4_proc_U0_p_0510_0_out_din");
    sc_trace(mVcdFile, match_x4_proc_U0_p_0510_0_out_write, "match_x4_proc_U0_p_0510_0_out_write");
    sc_trace(mVcdFile, ap_channel_done_compute2_V, "ap_channel_done_compute2_V");
    sc_trace(mVcdFile, match_x4_proc_U0_compute2_V1_full_n, "match_x4_proc_U0_compute2_V1_full_n");
    sc_trace(mVcdFile, i2_proc_U0_ap_start, "i2_proc_U0_ap_start");
    sc_trace(mVcdFile, i2_proc_U0_ap_done, "i2_proc_U0_ap_done");
    sc_trace(mVcdFile, i2_proc_U0_ap_continue, "i2_proc_U0_ap_continue");
    sc_trace(mVcdFile, i2_proc_U0_ap_idle, "i2_proc_U0_ap_idle");
    sc_trace(mVcdFile, i2_proc_U0_ap_ready, "i2_proc_U0_ap_ready");
    sc_trace(mVcdFile, i2_proc_U0_compute2_V1_address0, "i2_proc_U0_compute2_V1_address0");
    sc_trace(mVcdFile, i2_proc_U0_compute2_V1_ce0, "i2_proc_U0_compute2_V1_ce0");
    sc_trace(mVcdFile, i2_proc_U0_p_0510_0_read, "i2_proc_U0_p_0510_0_read");
    sc_trace(mVcdFile, i2_proc_U0_compute1_V_address0, "i2_proc_U0_compute1_V_address0");
    sc_trace(mVcdFile, i2_proc_U0_compute1_V_ce0, "i2_proc_U0_compute1_V_ce0");
    sc_trace(mVcdFile, i2_proc_U0_compute1_V_we0, "i2_proc_U0_compute1_V_we0");
    sc_trace(mVcdFile, i2_proc_U0_compute1_V_d0, "i2_proc_U0_compute1_V_d0");
    sc_trace(mVcdFile, i2_proc_U0_match2_read, "i2_proc_U0_match2_read");
    sc_trace(mVcdFile, i2_proc_U0_hcl_rdv3_V_address0, "i2_proc_U0_hcl_rdv3_V_address0");
    sc_trace(mVcdFile, i2_proc_U0_hcl_rdv3_V_ce0, "i2_proc_U0_hcl_rdv3_V_ce0");
    sc_trace(mVcdFile, i2_proc_U0_prototype_V_address0, "i2_proc_U0_prototype_V_address0");
    sc_trace(mVcdFile, i2_proc_U0_prototype_V_ce0, "i2_proc_U0_prototype_V_ce0");
    sc_trace(mVcdFile, i2_proc_U0_prototype_V_we0, "i2_proc_U0_prototype_V_we0");
    sc_trace(mVcdFile, i2_proc_U0_prototype_V_d0, "i2_proc_U0_prototype_V_d0");
    sc_trace(mVcdFile, i2_proc_U0_prototypeCounter_V_address0, "i2_proc_U0_prototypeCounter_V_address0");
    sc_trace(mVcdFile, i2_proc_U0_prototypeCounter_V_ce0, "i2_proc_U0_prototypeCounter_V_ce0");
    sc_trace(mVcdFile, i2_proc_U0_prototypeCounter_V_we0, "i2_proc_U0_prototypeCounter_V_we0");
    sc_trace(mVcdFile, i2_proc_U0_prototypeCounter_V_d0, "i2_proc_U0_prototypeCounter_V_d0");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, compute2_V_i_full_n, "compute2_V_i_full_n");
    sc_trace(mVcdFile, compute2_V_t_empty_n, "compute2_V_t_empty_n");
    sc_trace(mVcdFile, match2_channel_full_n, "match2_channel_full_n");
    sc_trace(mVcdFile, match2_channel_dout, "match2_channel_dout");
    sc_trace(mVcdFile, match2_channel_empty_n, "match2_channel_empty_n");
    sc_trace(mVcdFile, p_0510_0_c_full_n, "p_0510_0_c_full_n");
    sc_trace(mVcdFile, p_0510_0_c_dout, "p_0510_0_c_dout");
    sc_trace(mVcdFile, p_0510_0_c_empty_n, "p_0510_0_c_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_match_x4_proc_U0_ap_ready, "ap_sync_reg_match_x4_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_match_x4_proc_U0_ap_ready, "ap_sync_match_x4_proc_U0_ap_ready");
    sc_trace(mVcdFile, match_x4_proc_U0_ap_ready_count, "match_x4_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_i2_proc_U0_ap_ready, "ap_sync_reg_i2_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_i2_proc_U0_ap_ready, "ap_sync_i2_proc_U0_ap_ready");
    sc_trace(mVcdFile, i2_proc_U0_ap_ready_count, "i2_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, match_x4_proc_U0_start_full_n, "match_x4_proc_U0_start_full_n");
    sc_trace(mVcdFile, match_x4_proc_U0_start_write, "match_x4_proc_U0_start_write");
    sc_trace(mVcdFile, i2_proc_U0_start_full_n, "i2_proc_U0_start_full_n");
    sc_trace(mVcdFile, i2_proc_U0_start_write, "i2_proc_U0_start_write");
#endif

    }
}

dataflow_in_loop_lea::~dataflow_in_loop_lea() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete compute2_V_U;
    delete match_x4_proc_U0;
    delete i2_proc_U0;
    delete match2_channel_U;
    delete p_0510_0_c_U;
}

void dataflow_in_loop_lea::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_logic_1;
}

void dataflow_in_loop_lea::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void dataflow_in_loop_lea::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_sync_reg_i2_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_i2_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_i2_proc_U0_ap_ready = ap_sync_i2_proc_U0_ap_ready.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_sync_reg_match_x4_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_match_x4_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_match_x4_proc_U0_ap_ready = ap_sync_match_x4_proc_U0_ap_ready.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, i2_proc_U0_ap_ready.read()))) {
        i2_proc_U0_ap_ready_count = (!i2_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i2_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, i2_proc_U0_ap_ready.read()))) {
        i2_proc_U0_ap_ready_count = (!i2_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i2_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_0, match_x4_proc_U0_ap_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        match_x4_proc_U0_ap_ready_count = (!match_x4_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(match_x4_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, match_x4_proc_U0_ap_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()))) {
        match_x4_proc_U0_ap_ready_count = (!match_x4_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(match_x4_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
}

void dataflow_in_loop_lea::thread_ap_channel_done_compute2_V() {
    ap_channel_done_compute2_V = match_x4_proc_U0_ap_done.read();
}

void dataflow_in_loop_lea::thread_ap_done() {
    ap_done = i2_proc_U0_ap_done.read();
}

void dataflow_in_loop_lea::thread_ap_idle() {
    ap_idle = (match_x4_proc_U0_ap_idle.read() & i2_proc_U0_ap_idle.read() & (compute2_V_t_empty_n.read() ^ 
  ap_const_logic_1));
}

void dataflow_in_loop_lea::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void dataflow_in_loop_lea::thread_ap_sync_continue() {
    ap_sync_continue = ap_continue.read();
}

void dataflow_in_loop_lea::thread_ap_sync_done() {
    ap_sync_done = i2_proc_U0_ap_done.read();
}

void dataflow_in_loop_lea::thread_ap_sync_i2_proc_U0_ap_ready() {
    ap_sync_i2_proc_U0_ap_ready = (i2_proc_U0_ap_ready.read() | ap_sync_reg_i2_proc_U0_ap_ready.read());
}

void dataflow_in_loop_lea::thread_ap_sync_match_x4_proc_U0_ap_ready() {
    ap_sync_match_x4_proc_U0_ap_ready = (match_x4_proc_U0_ap_ready.read() | ap_sync_reg_match_x4_proc_U0_ap_ready.read());
}

void dataflow_in_loop_lea::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_match_x4_proc_U0_ap_ready.read() & ap_sync_i2_proc_U0_ap_ready.read());
}

void dataflow_in_loop_lea::thread_compute1_V_address0() {
    compute1_V_address0 = i2_proc_U0_compute1_V_address0.read();
}

void dataflow_in_loop_lea::thread_compute1_V_address1() {
    compute1_V_address1 = ap_const_lv5_0;
}

void dataflow_in_loop_lea::thread_compute1_V_ce0() {
    compute1_V_ce0 = i2_proc_U0_compute1_V_ce0.read();
}

void dataflow_in_loop_lea::thread_compute1_V_ce1() {
    compute1_V_ce1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_compute1_V_d0() {
    compute1_V_d0 = i2_proc_U0_compute1_V_d0.read();
}

void dataflow_in_loop_lea::thread_compute1_V_d1() {
    compute1_V_d1 = ap_const_lv32_0;
}

void dataflow_in_loop_lea::thread_compute1_V_we0() {
    compute1_V_we0 = i2_proc_U0_compute1_V_we0.read();
}

void dataflow_in_loop_lea::thread_compute1_V_we1() {
    compute1_V_we1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_hcl_in_train_V_address0() {
    hcl_in_train_V_address0 = match_x4_proc_U0_hcl_in_train_V_address0.read();
}

void dataflow_in_loop_lea::thread_hcl_in_train_V_address1() {
    hcl_in_train_V_address1 = ap_const_lv20_0;
}

void dataflow_in_loop_lea::thread_hcl_in_train_V_ce0() {
    hcl_in_train_V_ce0 = match_x4_proc_U0_hcl_in_train_V_ce0.read();
}

void dataflow_in_loop_lea::thread_hcl_in_train_V_ce1() {
    hcl_in_train_V_ce1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_hcl_in_train_V_d0() {
    hcl_in_train_V_d0 = ap_const_lv64_0;
}

void dataflow_in_loop_lea::thread_hcl_in_train_V_d1() {
    hcl_in_train_V_d1 = ap_const_lv64_0;
}

void dataflow_in_loop_lea::thread_hcl_in_train_V_we0() {
    hcl_in_train_V_we0 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_hcl_in_train_V_we1() {
    hcl_in_train_V_we1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_hcl_rdv3_V_address0() {
    hcl_rdv3_V_address0 = i2_proc_U0_hcl_rdv3_V_address0.read();
}

void dataflow_in_loop_lea::thread_hcl_rdv3_V_address1() {
    hcl_rdv3_V_address1 = ap_const_lv18_0;
}

void dataflow_in_loop_lea::thread_hcl_rdv3_V_ce0() {
    hcl_rdv3_V_ce0 = i2_proc_U0_hcl_rdv3_V_ce0.read();
}

void dataflow_in_loop_lea::thread_hcl_rdv3_V_ce1() {
    hcl_rdv3_V_ce1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_hcl_rdv3_V_d0() {
    hcl_rdv3_V_d0 = ap_const_lv64_0;
}

void dataflow_in_loop_lea::thread_hcl_rdv3_V_d1() {
    hcl_rdv3_V_d1 = ap_const_lv64_0;
}

void dataflow_in_loop_lea::thread_hcl_rdv3_V_we0() {
    hcl_rdv3_V_we0 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_hcl_rdv3_V_we1() {
    hcl_rdv3_V_we1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_hcl_trainLabels_V_address0() {
    hcl_trainLabels_V_address0 = match_x4_proc_U0_hcl_trainLabels_V_address0.read();
}

void dataflow_in_loop_lea::thread_hcl_trainLabels_V_address1() {
    hcl_trainLabels_V_address1 = ap_const_lv13_0;
}

void dataflow_in_loop_lea::thread_hcl_trainLabels_V_ce0() {
    hcl_trainLabels_V_ce0 = match_x4_proc_U0_hcl_trainLabels_V_ce0.read();
}

void dataflow_in_loop_lea::thread_hcl_trainLabels_V_ce1() {
    hcl_trainLabels_V_ce1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_hcl_trainLabels_V_d0() {
    hcl_trainLabels_V_d0 = ap_const_lv32_0;
}

void dataflow_in_loop_lea::thread_hcl_trainLabels_V_d1() {
    hcl_trainLabels_V_d1 = ap_const_lv32_0;
}

void dataflow_in_loop_lea::thread_hcl_trainLabels_V_we0() {
    hcl_trainLabels_V_we0 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_hcl_trainLabels_V_we1() {
    hcl_trainLabels_V_we1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_i2_proc_U0_ap_continue() {
    i2_proc_U0_ap_continue = ap_continue.read();
}

void dataflow_in_loop_lea::thread_i2_proc_U0_ap_start() {
    i2_proc_U0_ap_start = (ap_start.read() & compute2_V_t_empty_n.read() & (ap_sync_reg_i2_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void dataflow_in_loop_lea::thread_i2_proc_U0_start_full_n() {
    i2_proc_U0_start_full_n = ap_const_logic_1;
}

void dataflow_in_loop_lea::thread_i2_proc_U0_start_write() {
    i2_proc_U0_start_write = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_match_x4_proc_U0_ap_continue() {
    match_x4_proc_U0_ap_continue = compute2_V_i_full_n.read();
}

void dataflow_in_loop_lea::thread_match_x4_proc_U0_ap_start() {
    match_x4_proc_U0_ap_start = (ap_start.read() & (ap_sync_reg_match_x4_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void dataflow_in_loop_lea::thread_match_x4_proc_U0_compute2_V1_full_n() {
    match_x4_proc_U0_compute2_V1_full_n = compute2_V_i_full_n.read();
}

void dataflow_in_loop_lea::thread_match_x4_proc_U0_start_full_n() {
    match_x4_proc_U0_start_full_n = ap_const_logic_1;
}

void dataflow_in_loop_lea::thread_match_x4_proc_U0_start_write() {
    match_x4_proc_U0_start_write = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_prototypeCounter_V_address0() {
    prototypeCounter_V_address0 = i2_proc_U0_prototypeCounter_V_address0.read();
}

void dataflow_in_loop_lea::thread_prototypeCounter_V_address1() {
    prototypeCounter_V_address1 = ap_const_lv18_0;
}

void dataflow_in_loop_lea::thread_prototypeCounter_V_ce0() {
    prototypeCounter_V_ce0 = i2_proc_U0_prototypeCounter_V_ce0.read();
}

void dataflow_in_loop_lea::thread_prototypeCounter_V_ce1() {
    prototypeCounter_V_ce1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_prototypeCounter_V_d0() {
    prototypeCounter_V_d0 = i2_proc_U0_prototypeCounter_V_d0.read();
}

void dataflow_in_loop_lea::thread_prototypeCounter_V_d1() {
    prototypeCounter_V_d1 = ap_const_lv32_0;
}

void dataflow_in_loop_lea::thread_prototypeCounter_V_we0() {
    prototypeCounter_V_we0 = i2_proc_U0_prototypeCounter_V_we0.read();
}

void dataflow_in_loop_lea::thread_prototypeCounter_V_we1() {
    prototypeCounter_V_we1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_prototype_V_address0() {
    prototype_V_address0 = i2_proc_U0_prototype_V_address0.read();
}

void dataflow_in_loop_lea::thread_prototype_V_address1() {
    prototype_V_address1 = ap_const_lv12_0;
}

void dataflow_in_loop_lea::thread_prototype_V_ce0() {
    prototype_V_ce0 = i2_proc_U0_prototype_V_ce0.read();
}

void dataflow_in_loop_lea::thread_prototype_V_ce1() {
    prototype_V_ce1 = ap_const_logic_0;
}

void dataflow_in_loop_lea::thread_prototype_V_d0() {
    prototype_V_d0 = i2_proc_U0_prototype_V_d0.read();
}

void dataflow_in_loop_lea::thread_prototype_V_d1() {
    prototype_V_d1 = ap_const_lv64_0;
}

void dataflow_in_loop_lea::thread_prototype_V_we0() {
    prototype_V_we0 =  (sc_logic) (i2_proc_U0_prototype_V_we0.read()[0]);
}

void dataflow_in_loop_lea::thread_prototype_V_we1() {
    prototype_V_we1 = ap_const_logic_0;
}

}

