// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dataflow_parent_loop_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<13> dataflow_parent_loop_1::ap_const_lv13_0 = "0000000000000";
const sc_logic dataflow_parent_loop_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<32> dataflow_parent_loop_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<20> dataflow_parent_loop_1::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<64> dataflow_parent_loop_1::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<5> dataflow_parent_loop_1::ap_const_lv5_0 = "00000";
const sc_lv<18> dataflow_parent_loop_1::ap_const_lv18_0 = "000000000000000000";
const sc_lv<12> dataflow_parent_loop_1::ap_const_lv12_0 = "000000000000";
const sc_logic dataflow_parent_loop_1::ap_const_logic_1 = sc_dt::Log_1;
const bool dataflow_parent_loop_1::ap_const_boolean_1 = true;
const sc_lv<5> dataflow_parent_loop_1::ap_const_lv5_1A = "11010";
const sc_lv<5> dataflow_parent_loop_1::ap_const_lv5_1 = "1";
const sc_lv<32> dataflow_parent_loop_1::ap_const_lv32_1 = "1";
const sc_lv<64> dataflow_parent_loop_1::ap_const_lv64_1 = "1";

dataflow_parent_loop_1::dataflow_parent_loop_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dataflow_in_loop_lea_U0 = new dataflow_in_loop_lea("dataflow_in_loop_lea_U0");
    dataflow_in_loop_lea_U0->ap_clk(ap_clk);
    dataflow_in_loop_lea_U0->ap_rst(ap_rst);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_address0(dataflow_in_loop_lea_U0_hcl_trainLabels_V_address0);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_ce0(dataflow_in_loop_lea_U0_hcl_trainLabels_V_ce0);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_d0(dataflow_in_loop_lea_U0_hcl_trainLabels_V_d0);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_q0(hcl_trainLabels_V_q0);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_we0(dataflow_in_loop_lea_U0_hcl_trainLabels_V_we0);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_address1(dataflow_in_loop_lea_U0_hcl_trainLabels_V_address1);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_ce1(dataflow_in_loop_lea_U0_hcl_trainLabels_V_ce1);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_d1(dataflow_in_loop_lea_U0_hcl_trainLabels_V_d1);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_q1(ap_var_for_const0);
    dataflow_in_loop_lea_U0->hcl_trainLabels_V_we1(dataflow_in_loop_lea_U0_hcl_trainLabels_V_we1);
    dataflow_in_loop_lea_U0->p_0510_0(loop_dataflow_input_count);
    dataflow_in_loop_lea_U0->hcl_in_train_V_address0(dataflow_in_loop_lea_U0_hcl_in_train_V_address0);
    dataflow_in_loop_lea_U0->hcl_in_train_V_ce0(dataflow_in_loop_lea_U0_hcl_in_train_V_ce0);
    dataflow_in_loop_lea_U0->hcl_in_train_V_d0(dataflow_in_loop_lea_U0_hcl_in_train_V_d0);
    dataflow_in_loop_lea_U0->hcl_in_train_V_q0(hcl_in_train_V_q0);
    dataflow_in_loop_lea_U0->hcl_in_train_V_we0(dataflow_in_loop_lea_U0_hcl_in_train_V_we0);
    dataflow_in_loop_lea_U0->hcl_in_train_V_address1(dataflow_in_loop_lea_U0_hcl_in_train_V_address1);
    dataflow_in_loop_lea_U0->hcl_in_train_V_ce1(dataflow_in_loop_lea_U0_hcl_in_train_V_ce1);
    dataflow_in_loop_lea_U0->hcl_in_train_V_d1(dataflow_in_loop_lea_U0_hcl_in_train_V_d1);
    dataflow_in_loop_lea_U0->hcl_in_train_V_q1(ap_var_for_const1);
    dataflow_in_loop_lea_U0->hcl_in_train_V_we1(dataflow_in_loop_lea_U0_hcl_in_train_V_we1);
    dataflow_in_loop_lea_U0->compute1_V_address0(dataflow_in_loop_lea_U0_compute1_V_address0);
    dataflow_in_loop_lea_U0->compute1_V_ce0(dataflow_in_loop_lea_U0_compute1_V_ce0);
    dataflow_in_loop_lea_U0->compute1_V_d0(dataflow_in_loop_lea_U0_compute1_V_d0);
    dataflow_in_loop_lea_U0->compute1_V_q0(ap_var_for_const0);
    dataflow_in_loop_lea_U0->compute1_V_we0(dataflow_in_loop_lea_U0_compute1_V_we0);
    dataflow_in_loop_lea_U0->compute1_V_address1(dataflow_in_loop_lea_U0_compute1_V_address1);
    dataflow_in_loop_lea_U0->compute1_V_ce1(dataflow_in_loop_lea_U0_compute1_V_ce1);
    dataflow_in_loop_lea_U0->compute1_V_d1(dataflow_in_loop_lea_U0_compute1_V_d1);
    dataflow_in_loop_lea_U0->compute1_V_q1(ap_var_for_const0);
    dataflow_in_loop_lea_U0->compute1_V_we1(dataflow_in_loop_lea_U0_compute1_V_we1);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_address0(dataflow_in_loop_lea_U0_hcl_rdv3_V_address0);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_ce0(dataflow_in_loop_lea_U0_hcl_rdv3_V_ce0);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_d0(dataflow_in_loop_lea_U0_hcl_rdv3_V_d0);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_q0(hcl_rdv3_V_q0);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_we0(dataflow_in_loop_lea_U0_hcl_rdv3_V_we0);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_address1(dataflow_in_loop_lea_U0_hcl_rdv3_V_address1);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_ce1(dataflow_in_loop_lea_U0_hcl_rdv3_V_ce1);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_d1(dataflow_in_loop_lea_U0_hcl_rdv3_V_d1);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_q1(ap_var_for_const1);
    dataflow_in_loop_lea_U0->hcl_rdv3_V_we1(dataflow_in_loop_lea_U0_hcl_rdv3_V_we1);
    dataflow_in_loop_lea_U0->prototype_V_address0(dataflow_in_loop_lea_U0_prototype_V_address0);
    dataflow_in_loop_lea_U0->prototype_V_ce0(dataflow_in_loop_lea_U0_prototype_V_ce0);
    dataflow_in_loop_lea_U0->prototype_V_d0(dataflow_in_loop_lea_U0_prototype_V_d0);
    dataflow_in_loop_lea_U0->prototype_V_q0(ap_var_for_const1);
    dataflow_in_loop_lea_U0->prototype_V_we0(dataflow_in_loop_lea_U0_prototype_V_we0);
    dataflow_in_loop_lea_U0->prototype_V_address1(dataflow_in_loop_lea_U0_prototype_V_address1);
    dataflow_in_loop_lea_U0->prototype_V_ce1(dataflow_in_loop_lea_U0_prototype_V_ce1);
    dataflow_in_loop_lea_U0->prototype_V_d1(dataflow_in_loop_lea_U0_prototype_V_d1);
    dataflow_in_loop_lea_U0->prototype_V_q1(ap_var_for_const1);
    dataflow_in_loop_lea_U0->prototype_V_we1(dataflow_in_loop_lea_U0_prototype_V_we1);
    dataflow_in_loop_lea_U0->prototypeCounter_V_address0(dataflow_in_loop_lea_U0_prototypeCounter_V_address0);
    dataflow_in_loop_lea_U0->prototypeCounter_V_ce0(dataflow_in_loop_lea_U0_prototypeCounter_V_ce0);
    dataflow_in_loop_lea_U0->prototypeCounter_V_d0(dataflow_in_loop_lea_U0_prototypeCounter_V_d0);
    dataflow_in_loop_lea_U0->prototypeCounter_V_q0(ap_var_for_const0);
    dataflow_in_loop_lea_U0->prototypeCounter_V_we0(dataflow_in_loop_lea_U0_prototypeCounter_V_we0);
    dataflow_in_loop_lea_U0->prototypeCounter_V_address1(dataflow_in_loop_lea_U0_prototypeCounter_V_address1);
    dataflow_in_loop_lea_U0->prototypeCounter_V_ce1(dataflow_in_loop_lea_U0_prototypeCounter_V_ce1);
    dataflow_in_loop_lea_U0->prototypeCounter_V_d1(dataflow_in_loop_lea_U0_prototypeCounter_V_d1);
    dataflow_in_loop_lea_U0->prototypeCounter_V_q1(ap_var_for_const0);
    dataflow_in_loop_lea_U0->prototypeCounter_V_we1(dataflow_in_loop_lea_U0_prototypeCounter_V_we1);
    dataflow_in_loop_lea_U0->p_0510_0_ap_vld(ap_var_for_const2);
    dataflow_in_loop_lea_U0->ap_start(dataflow_in_loop_lea_U0_ap_start);
    dataflow_in_loop_lea_U0->ap_done(dataflow_in_loop_lea_U0_ap_done);
    dataflow_in_loop_lea_U0->ap_ready(dataflow_in_loop_lea_U0_ap_ready);
    dataflow_in_loop_lea_U0->ap_idle(dataflow_in_loop_lea_U0_ap_idle);
    dataflow_in_loop_lea_U0->ap_continue(dataflow_in_loop_lea_U0_ap_continue);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( dataflow_in_loop_lea_U0_ap_done );
    sensitive << ( loop_dataflow_output_count );
    sensitive << ( bound_minus_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( dataflow_in_loop_lea_U0_ap_idle );
    sensitive << ( ap_start );
    sensitive << ( loop_dataflow_output_count );

    SC_METHOD(thread_ap_ready);
    sensitive << ( dataflow_in_loop_lea_U0_ap_ready );
    sensitive << ( ap_start );
    sensitive << ( loop_dataflow_input_count );
    sensitive << ( bound_minus_1 );

    SC_METHOD(thread_ap_sync_continue);
    sensitive << ( ap_continue );

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( dataflow_in_loop_lea_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( dataflow_in_loop_lea_U0_ap_ready );

    SC_METHOD(thread_bound_minus_1);

    SC_METHOD(thread_compute1_V_address0);
    sensitive << ( dataflow_in_loop_lea_U0_compute1_V_address0 );

    SC_METHOD(thread_compute1_V_address1);

    SC_METHOD(thread_compute1_V_ce0);
    sensitive << ( dataflow_in_loop_lea_U0_compute1_V_ce0 );

    SC_METHOD(thread_compute1_V_ce1);

    SC_METHOD(thread_compute1_V_d0);
    sensitive << ( dataflow_in_loop_lea_U0_compute1_V_d0 );

    SC_METHOD(thread_compute1_V_d1);

    SC_METHOD(thread_compute1_V_we0);
    sensitive << ( dataflow_in_loop_lea_U0_compute1_V_we0 );

    SC_METHOD(thread_compute1_V_we1);

    SC_METHOD(thread_dataflow_in_loop_lea_U0_ap_continue);
    sensitive << ( ap_continue );
    sensitive << ( loop_dataflow_output_count );
    sensitive << ( bound_minus_1 );

    SC_METHOD(thread_dataflow_in_loop_lea_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_dataflow_in_loop_lea_U0_start_full_n);

    SC_METHOD(thread_dataflow_in_loop_lea_U0_start_write);

    SC_METHOD(thread_hcl_in_train_V_address0);
    sensitive << ( dataflow_in_loop_lea_U0_hcl_in_train_V_address0 );

    SC_METHOD(thread_hcl_in_train_V_address1);

    SC_METHOD(thread_hcl_in_train_V_ce0);
    sensitive << ( dataflow_in_loop_lea_U0_hcl_in_train_V_ce0 );

    SC_METHOD(thread_hcl_in_train_V_ce1);

    SC_METHOD(thread_hcl_in_train_V_d0);

    SC_METHOD(thread_hcl_in_train_V_d1);

    SC_METHOD(thread_hcl_in_train_V_we0);

    SC_METHOD(thread_hcl_in_train_V_we1);

    SC_METHOD(thread_hcl_rdv3_V_address0);
    sensitive << ( dataflow_in_loop_lea_U0_hcl_rdv3_V_address0 );

    SC_METHOD(thread_hcl_rdv3_V_address1);

    SC_METHOD(thread_hcl_rdv3_V_ce0);
    sensitive << ( dataflow_in_loop_lea_U0_hcl_rdv3_V_ce0 );

    SC_METHOD(thread_hcl_rdv3_V_ce1);

    SC_METHOD(thread_hcl_rdv3_V_d0);

    SC_METHOD(thread_hcl_rdv3_V_d1);

    SC_METHOD(thread_hcl_rdv3_V_we0);

    SC_METHOD(thread_hcl_rdv3_V_we1);

    SC_METHOD(thread_hcl_trainLabels_V_address0);
    sensitive << ( dataflow_in_loop_lea_U0_hcl_trainLabels_V_address0 );

    SC_METHOD(thread_hcl_trainLabels_V_address1);

    SC_METHOD(thread_hcl_trainLabels_V_ce0);
    sensitive << ( dataflow_in_loop_lea_U0_hcl_trainLabels_V_ce0 );

    SC_METHOD(thread_hcl_trainLabels_V_ce1);

    SC_METHOD(thread_hcl_trainLabels_V_d0);

    SC_METHOD(thread_hcl_trainLabels_V_d1);

    SC_METHOD(thread_hcl_trainLabels_V_we0);

    SC_METHOD(thread_hcl_trainLabels_V_we1);

    SC_METHOD(thread_prototypeCounter_V_address0);
    sensitive << ( dataflow_in_loop_lea_U0_prototypeCounter_V_address0 );

    SC_METHOD(thread_prototypeCounter_V_address1);

    SC_METHOD(thread_prototypeCounter_V_ce0);
    sensitive << ( dataflow_in_loop_lea_U0_prototypeCounter_V_ce0 );

    SC_METHOD(thread_prototypeCounter_V_ce1);

    SC_METHOD(thread_prototypeCounter_V_d0);
    sensitive << ( dataflow_in_loop_lea_U0_prototypeCounter_V_d0 );

    SC_METHOD(thread_prototypeCounter_V_d1);

    SC_METHOD(thread_prototypeCounter_V_we0);
    sensitive << ( dataflow_in_loop_lea_U0_prototypeCounter_V_we0 );

    SC_METHOD(thread_prototypeCounter_V_we1);

    SC_METHOD(thread_prototype_V_address0);
    sensitive << ( dataflow_in_loop_lea_U0_prototype_V_address0 );

    SC_METHOD(thread_prototype_V_address1);

    SC_METHOD(thread_prototype_V_ce0);
    sensitive << ( dataflow_in_loop_lea_U0_prototype_V_ce0 );

    SC_METHOD(thread_prototype_V_ce1);

    SC_METHOD(thread_prototype_V_d0);
    sensitive << ( dataflow_in_loop_lea_U0_prototype_V_d0 );

    SC_METHOD(thread_prototype_V_d1);

    SC_METHOD(thread_prototype_V_we0);
    sensitive << ( dataflow_in_loop_lea_U0_prototype_V_we0 );

    SC_METHOD(thread_prototype_V_we1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    loop_dataflow_input_count = "00000";
    loop_dataflow_output_count = "00000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dataflow_parent_loop_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, hcl_trainLabels_V_address0, "(port)hcl_trainLabels_V_address0");
    sc_trace(mVcdFile, hcl_trainLabels_V_ce0, "(port)hcl_trainLabels_V_ce0");
    sc_trace(mVcdFile, hcl_trainLabels_V_d0, "(port)hcl_trainLabels_V_d0");
    sc_trace(mVcdFile, hcl_trainLabels_V_q0, "(port)hcl_trainLabels_V_q0");
    sc_trace(mVcdFile, hcl_trainLabels_V_we0, "(port)hcl_trainLabels_V_we0");
    sc_trace(mVcdFile, hcl_trainLabels_V_address1, "(port)hcl_trainLabels_V_address1");
    sc_trace(mVcdFile, hcl_trainLabels_V_ce1, "(port)hcl_trainLabels_V_ce1");
    sc_trace(mVcdFile, hcl_trainLabels_V_d1, "(port)hcl_trainLabels_V_d1");
    sc_trace(mVcdFile, hcl_trainLabels_V_q1, "(port)hcl_trainLabels_V_q1");
    sc_trace(mVcdFile, hcl_trainLabels_V_we1, "(port)hcl_trainLabels_V_we1");
    sc_trace(mVcdFile, hcl_in_train_V_address0, "(port)hcl_in_train_V_address0");
    sc_trace(mVcdFile, hcl_in_train_V_ce0, "(port)hcl_in_train_V_ce0");
    sc_trace(mVcdFile, hcl_in_train_V_d0, "(port)hcl_in_train_V_d0");
    sc_trace(mVcdFile, hcl_in_train_V_q0, "(port)hcl_in_train_V_q0");
    sc_trace(mVcdFile, hcl_in_train_V_we0, "(port)hcl_in_train_V_we0");
    sc_trace(mVcdFile, hcl_in_train_V_address1, "(port)hcl_in_train_V_address1");
    sc_trace(mVcdFile, hcl_in_train_V_ce1, "(port)hcl_in_train_V_ce1");
    sc_trace(mVcdFile, hcl_in_train_V_d1, "(port)hcl_in_train_V_d1");
    sc_trace(mVcdFile, hcl_in_train_V_q1, "(port)hcl_in_train_V_q1");
    sc_trace(mVcdFile, hcl_in_train_V_we1, "(port)hcl_in_train_V_we1");
    sc_trace(mVcdFile, compute1_V_address0, "(port)compute1_V_address0");
    sc_trace(mVcdFile, compute1_V_ce0, "(port)compute1_V_ce0");
    sc_trace(mVcdFile, compute1_V_d0, "(port)compute1_V_d0");
    sc_trace(mVcdFile, compute1_V_q0, "(port)compute1_V_q0");
    sc_trace(mVcdFile, compute1_V_we0, "(port)compute1_V_we0");
    sc_trace(mVcdFile, compute1_V_address1, "(port)compute1_V_address1");
    sc_trace(mVcdFile, compute1_V_ce1, "(port)compute1_V_ce1");
    sc_trace(mVcdFile, compute1_V_d1, "(port)compute1_V_d1");
    sc_trace(mVcdFile, compute1_V_q1, "(port)compute1_V_q1");
    sc_trace(mVcdFile, compute1_V_we1, "(port)compute1_V_we1");
    sc_trace(mVcdFile, hcl_rdv3_V_address0, "(port)hcl_rdv3_V_address0");
    sc_trace(mVcdFile, hcl_rdv3_V_ce0, "(port)hcl_rdv3_V_ce0");
    sc_trace(mVcdFile, hcl_rdv3_V_d0, "(port)hcl_rdv3_V_d0");
    sc_trace(mVcdFile, hcl_rdv3_V_q0, "(port)hcl_rdv3_V_q0");
    sc_trace(mVcdFile, hcl_rdv3_V_we0, "(port)hcl_rdv3_V_we0");
    sc_trace(mVcdFile, hcl_rdv3_V_address1, "(port)hcl_rdv3_V_address1");
    sc_trace(mVcdFile, hcl_rdv3_V_ce1, "(port)hcl_rdv3_V_ce1");
    sc_trace(mVcdFile, hcl_rdv3_V_d1, "(port)hcl_rdv3_V_d1");
    sc_trace(mVcdFile, hcl_rdv3_V_q1, "(port)hcl_rdv3_V_q1");
    sc_trace(mVcdFile, hcl_rdv3_V_we1, "(port)hcl_rdv3_V_we1");
    sc_trace(mVcdFile, prototype_V_address0, "(port)prototype_V_address0");
    sc_trace(mVcdFile, prototype_V_ce0, "(port)prototype_V_ce0");
    sc_trace(mVcdFile, prototype_V_d0, "(port)prototype_V_d0");
    sc_trace(mVcdFile, prototype_V_q0, "(port)prototype_V_q0");
    sc_trace(mVcdFile, prototype_V_we0, "(port)prototype_V_we0");
    sc_trace(mVcdFile, prototype_V_address1, "(port)prototype_V_address1");
    sc_trace(mVcdFile, prototype_V_ce1, "(port)prototype_V_ce1");
    sc_trace(mVcdFile, prototype_V_d1, "(port)prototype_V_d1");
    sc_trace(mVcdFile, prototype_V_q1, "(port)prototype_V_q1");
    sc_trace(mVcdFile, prototype_V_we1, "(port)prototype_V_we1");
    sc_trace(mVcdFile, prototypeCounter_V_address0, "(port)prototypeCounter_V_address0");
    sc_trace(mVcdFile, prototypeCounter_V_ce0, "(port)prototypeCounter_V_ce0");
    sc_trace(mVcdFile, prototypeCounter_V_d0, "(port)prototypeCounter_V_d0");
    sc_trace(mVcdFile, prototypeCounter_V_q0, "(port)prototypeCounter_V_q0");
    sc_trace(mVcdFile, prototypeCounter_V_we0, "(port)prototypeCounter_V_we0");
    sc_trace(mVcdFile, prototypeCounter_V_address1, "(port)prototypeCounter_V_address1");
    sc_trace(mVcdFile, prototypeCounter_V_ce1, "(port)prototypeCounter_V_ce1");
    sc_trace(mVcdFile, prototypeCounter_V_d1, "(port)prototypeCounter_V_d1");
    sc_trace(mVcdFile, prototypeCounter_V_q1, "(port)prototypeCounter_V_q1");
    sc_trace(mVcdFile, prototypeCounter_V_we1, "(port)prototypeCounter_V_we1");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_trainLabels_V_address0, "dataflow_in_loop_lea_U0_hcl_trainLabels_V_address0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_trainLabels_V_ce0, "dataflow_in_loop_lea_U0_hcl_trainLabels_V_ce0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_trainLabels_V_d0, "dataflow_in_loop_lea_U0_hcl_trainLabels_V_d0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_trainLabels_V_we0, "dataflow_in_loop_lea_U0_hcl_trainLabels_V_we0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_trainLabels_V_address1, "dataflow_in_loop_lea_U0_hcl_trainLabels_V_address1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_trainLabels_V_ce1, "dataflow_in_loop_lea_U0_hcl_trainLabels_V_ce1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_trainLabels_V_d1, "dataflow_in_loop_lea_U0_hcl_trainLabels_V_d1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_trainLabels_V_we1, "dataflow_in_loop_lea_U0_hcl_trainLabels_V_we1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_in_train_V_address0, "dataflow_in_loop_lea_U0_hcl_in_train_V_address0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_in_train_V_ce0, "dataflow_in_loop_lea_U0_hcl_in_train_V_ce0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_in_train_V_d0, "dataflow_in_loop_lea_U0_hcl_in_train_V_d0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_in_train_V_we0, "dataflow_in_loop_lea_U0_hcl_in_train_V_we0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_in_train_V_address1, "dataflow_in_loop_lea_U0_hcl_in_train_V_address1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_in_train_V_ce1, "dataflow_in_loop_lea_U0_hcl_in_train_V_ce1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_in_train_V_d1, "dataflow_in_loop_lea_U0_hcl_in_train_V_d1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_in_train_V_we1, "dataflow_in_loop_lea_U0_hcl_in_train_V_we1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_compute1_V_address0, "dataflow_in_loop_lea_U0_compute1_V_address0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_compute1_V_ce0, "dataflow_in_loop_lea_U0_compute1_V_ce0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_compute1_V_d0, "dataflow_in_loop_lea_U0_compute1_V_d0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_compute1_V_we0, "dataflow_in_loop_lea_U0_compute1_V_we0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_compute1_V_address1, "dataflow_in_loop_lea_U0_compute1_V_address1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_compute1_V_ce1, "dataflow_in_loop_lea_U0_compute1_V_ce1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_compute1_V_d1, "dataflow_in_loop_lea_U0_compute1_V_d1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_compute1_V_we1, "dataflow_in_loop_lea_U0_compute1_V_we1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_rdv3_V_address0, "dataflow_in_loop_lea_U0_hcl_rdv3_V_address0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_rdv3_V_ce0, "dataflow_in_loop_lea_U0_hcl_rdv3_V_ce0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_rdv3_V_d0, "dataflow_in_loop_lea_U0_hcl_rdv3_V_d0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_rdv3_V_we0, "dataflow_in_loop_lea_U0_hcl_rdv3_V_we0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_rdv3_V_address1, "dataflow_in_loop_lea_U0_hcl_rdv3_V_address1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_rdv3_V_ce1, "dataflow_in_loop_lea_U0_hcl_rdv3_V_ce1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_rdv3_V_d1, "dataflow_in_loop_lea_U0_hcl_rdv3_V_d1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_hcl_rdv3_V_we1, "dataflow_in_loop_lea_U0_hcl_rdv3_V_we1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototype_V_address0, "dataflow_in_loop_lea_U0_prototype_V_address0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototype_V_ce0, "dataflow_in_loop_lea_U0_prototype_V_ce0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototype_V_d0, "dataflow_in_loop_lea_U0_prototype_V_d0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototype_V_we0, "dataflow_in_loop_lea_U0_prototype_V_we0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototype_V_address1, "dataflow_in_loop_lea_U0_prototype_V_address1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototype_V_ce1, "dataflow_in_loop_lea_U0_prototype_V_ce1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototype_V_d1, "dataflow_in_loop_lea_U0_prototype_V_d1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototype_V_we1, "dataflow_in_loop_lea_U0_prototype_V_we1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototypeCounter_V_address0, "dataflow_in_loop_lea_U0_prototypeCounter_V_address0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototypeCounter_V_ce0, "dataflow_in_loop_lea_U0_prototypeCounter_V_ce0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototypeCounter_V_d0, "dataflow_in_loop_lea_U0_prototypeCounter_V_d0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototypeCounter_V_we0, "dataflow_in_loop_lea_U0_prototypeCounter_V_we0");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototypeCounter_V_address1, "dataflow_in_loop_lea_U0_prototypeCounter_V_address1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototypeCounter_V_ce1, "dataflow_in_loop_lea_U0_prototypeCounter_V_ce1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototypeCounter_V_d1, "dataflow_in_loop_lea_U0_prototypeCounter_V_d1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_prototypeCounter_V_we1, "dataflow_in_loop_lea_U0_prototypeCounter_V_we1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_ap_start, "dataflow_in_loop_lea_U0_ap_start");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_ap_done, "dataflow_in_loop_lea_U0_ap_done");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_ap_ready, "dataflow_in_loop_lea_U0_ap_ready");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_ap_idle, "dataflow_in_loop_lea_U0_ap_idle");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_ap_continue, "dataflow_in_loop_lea_U0_ap_continue");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, loop_dataflow_input_count, "loop_dataflow_input_count");
    sc_trace(mVcdFile, loop_dataflow_output_count, "loop_dataflow_output_count");
    sc_trace(mVcdFile, bound_minus_1, "bound_minus_1");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_start_full_n, "dataflow_in_loop_lea_U0_start_full_n");
    sc_trace(mVcdFile, dataflow_in_loop_lea_U0_start_write, "dataflow_in_loop_lea_U0_start_write");
#endif

    }
}

dataflow_parent_loop_1::~dataflow_parent_loop_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dataflow_in_loop_lea_U0;
}

void dataflow_parent_loop_1::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_0;
}

void dataflow_parent_loop_1::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_0;
}

void dataflow_parent_loop_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        loop_dataflow_input_count = ap_const_lv5_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
             esl_seteq<1,1,1>(dataflow_in_loop_lea_U0_ap_ready.read(), ap_const_logic_1) && 
             !esl_seteq<1,5,5>(loop_dataflow_input_count.read(), bound_minus_1.read()))) {
            loop_dataflow_input_count = (!loop_dataflow_input_count.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(loop_dataflow_input_count.read()) + sc_biguint<5>(ap_const_lv5_1));
        } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                    esl_seteq<1,1,1>(dataflow_in_loop_lea_U0_ap_ready.read(), ap_const_logic_1) && 
                    esl_seteq<1,5,5>(loop_dataflow_input_count.read(), bound_minus_1.read()))) {
            loop_dataflow_input_count = ap_const_lv5_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        loop_dataflow_output_count = ap_const_lv5_0;
    } else {
        if ((esl_seteq<1,1,1>(dataflow_in_loop_lea_U0_ap_done.read(), ap_const_logic_1) && 
             esl_seteq<1,1,1>(dataflow_in_loop_lea_U0_ap_continue.read(), ap_const_logic_1) && 
             !esl_seteq<1,5,5>(loop_dataflow_output_count.read(), bound_minus_1.read()))) {
            loop_dataflow_output_count = (!loop_dataflow_output_count.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(loop_dataflow_output_count.read()) + sc_biguint<5>(ap_const_lv5_1));
        } else if ((esl_seteq<1,1,1>(dataflow_in_loop_lea_U0_ap_done.read(), ap_const_logic_1) && 
                    esl_seteq<1,1,1>(dataflow_in_loop_lea_U0_ap_continue.read(), ap_const_logic_1) && 
                    esl_seteq<1,5,5>(loop_dataflow_output_count.read(), bound_minus_1.read()))) {
            loop_dataflow_output_count = ap_const_lv5_0;
        }
    }
}

void dataflow_parent_loop_1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(dataflow_in_loop_lea_U0_ap_done.read(), ap_const_logic_1) && 
         esl_seteq<1,5,5>(loop_dataflow_output_count.read(), bound_minus_1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dataflow_parent_loop_1::thread_ap_idle() {
    if ((esl_seteq<1,5,5>(ap_const_lv5_0, loop_dataflow_output_count.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(dataflow_in_loop_lea_U0_ap_idle.read(), ap_const_logic_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dataflow_parent_loop_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(dataflow_in_loop_lea_U0_ap_ready.read(), ap_const_logic_1) && 
         esl_seteq<1,5,5>(loop_dataflow_input_count.read(), bound_minus_1.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dataflow_parent_loop_1::thread_ap_sync_continue() {
    ap_sync_continue = ap_continue.read();
}

void dataflow_parent_loop_1::thread_ap_sync_done() {
    ap_sync_done = dataflow_in_loop_lea_U0_ap_done.read();
}

void dataflow_parent_loop_1::thread_ap_sync_ready() {
    ap_sync_ready = dataflow_in_loop_lea_U0_ap_ready.read();
}

void dataflow_parent_loop_1::thread_bound_minus_1() {
    bound_minus_1 = (!ap_const_lv5_1A.is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_1A) - sc_biguint<5>(ap_const_lv5_1));
}

void dataflow_parent_loop_1::thread_compute1_V_address0() {
    compute1_V_address0 = dataflow_in_loop_lea_U0_compute1_V_address0.read();
}

void dataflow_parent_loop_1::thread_compute1_V_address1() {
    compute1_V_address1 = ap_const_lv5_0;
}

void dataflow_parent_loop_1::thread_compute1_V_ce0() {
    compute1_V_ce0 = dataflow_in_loop_lea_U0_compute1_V_ce0.read();
}

void dataflow_parent_loop_1::thread_compute1_V_ce1() {
    compute1_V_ce1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_compute1_V_d0() {
    compute1_V_d0 = dataflow_in_loop_lea_U0_compute1_V_d0.read();
}

void dataflow_parent_loop_1::thread_compute1_V_d1() {
    compute1_V_d1 = ap_const_lv32_0;
}

void dataflow_parent_loop_1::thread_compute1_V_we0() {
    compute1_V_we0 = dataflow_in_loop_lea_U0_compute1_V_we0.read();
}

void dataflow_parent_loop_1::thread_compute1_V_we1() {
    compute1_V_we1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_dataflow_in_loop_lea_U0_ap_continue() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read()) || 
         !esl_seteq<1,5,5>(loop_dataflow_output_count.read(), bound_minus_1.read()))) {
        dataflow_in_loop_lea_U0_ap_continue = ap_const_logic_1;
    } else {
        dataflow_in_loop_lea_U0_ap_continue = ap_const_logic_0;
    }
}

void dataflow_parent_loop_1::thread_dataflow_in_loop_lea_U0_ap_start() {
    dataflow_in_loop_lea_U0_ap_start = ap_start.read();
}

void dataflow_parent_loop_1::thread_dataflow_in_loop_lea_U0_start_full_n() {
    dataflow_in_loop_lea_U0_start_full_n = ap_const_logic_1;
}

void dataflow_parent_loop_1::thread_dataflow_in_loop_lea_U0_start_write() {
    dataflow_in_loop_lea_U0_start_write = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_hcl_in_train_V_address0() {
    hcl_in_train_V_address0 = dataflow_in_loop_lea_U0_hcl_in_train_V_address0.read();
}

void dataflow_parent_loop_1::thread_hcl_in_train_V_address1() {
    hcl_in_train_V_address1 = ap_const_lv20_0;
}

void dataflow_parent_loop_1::thread_hcl_in_train_V_ce0() {
    hcl_in_train_V_ce0 = dataflow_in_loop_lea_U0_hcl_in_train_V_ce0.read();
}

void dataflow_parent_loop_1::thread_hcl_in_train_V_ce1() {
    hcl_in_train_V_ce1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_hcl_in_train_V_d0() {
    hcl_in_train_V_d0 = ap_const_lv64_0;
}

void dataflow_parent_loop_1::thread_hcl_in_train_V_d1() {
    hcl_in_train_V_d1 = ap_const_lv64_0;
}

void dataflow_parent_loop_1::thread_hcl_in_train_V_we0() {
    hcl_in_train_V_we0 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_hcl_in_train_V_we1() {
    hcl_in_train_V_we1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_hcl_rdv3_V_address0() {
    hcl_rdv3_V_address0 = dataflow_in_loop_lea_U0_hcl_rdv3_V_address0.read();
}

void dataflow_parent_loop_1::thread_hcl_rdv3_V_address1() {
    hcl_rdv3_V_address1 = ap_const_lv18_0;
}

void dataflow_parent_loop_1::thread_hcl_rdv3_V_ce0() {
    hcl_rdv3_V_ce0 = dataflow_in_loop_lea_U0_hcl_rdv3_V_ce0.read();
}

void dataflow_parent_loop_1::thread_hcl_rdv3_V_ce1() {
    hcl_rdv3_V_ce1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_hcl_rdv3_V_d0() {
    hcl_rdv3_V_d0 = ap_const_lv64_0;
}

void dataflow_parent_loop_1::thread_hcl_rdv3_V_d1() {
    hcl_rdv3_V_d1 = ap_const_lv64_0;
}

void dataflow_parent_loop_1::thread_hcl_rdv3_V_we0() {
    hcl_rdv3_V_we0 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_hcl_rdv3_V_we1() {
    hcl_rdv3_V_we1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_hcl_trainLabels_V_address0() {
    hcl_trainLabels_V_address0 = dataflow_in_loop_lea_U0_hcl_trainLabels_V_address0.read();
}

void dataflow_parent_loop_1::thread_hcl_trainLabels_V_address1() {
    hcl_trainLabels_V_address1 = ap_const_lv13_0;
}

void dataflow_parent_loop_1::thread_hcl_trainLabels_V_ce0() {
    hcl_trainLabels_V_ce0 = dataflow_in_loop_lea_U0_hcl_trainLabels_V_ce0.read();
}

void dataflow_parent_loop_1::thread_hcl_trainLabels_V_ce1() {
    hcl_trainLabels_V_ce1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_hcl_trainLabels_V_d0() {
    hcl_trainLabels_V_d0 = ap_const_lv32_0;
}

void dataflow_parent_loop_1::thread_hcl_trainLabels_V_d1() {
    hcl_trainLabels_V_d1 = ap_const_lv32_0;
}

void dataflow_parent_loop_1::thread_hcl_trainLabels_V_we0() {
    hcl_trainLabels_V_we0 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_hcl_trainLabels_V_we1() {
    hcl_trainLabels_V_we1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_prototypeCounter_V_address0() {
    prototypeCounter_V_address0 = dataflow_in_loop_lea_U0_prototypeCounter_V_address0.read();
}

void dataflow_parent_loop_1::thread_prototypeCounter_V_address1() {
    prototypeCounter_V_address1 = ap_const_lv18_0;
}

void dataflow_parent_loop_1::thread_prototypeCounter_V_ce0() {
    prototypeCounter_V_ce0 = dataflow_in_loop_lea_U0_prototypeCounter_V_ce0.read();
}

void dataflow_parent_loop_1::thread_prototypeCounter_V_ce1() {
    prototypeCounter_V_ce1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_prototypeCounter_V_d0() {
    prototypeCounter_V_d0 = dataflow_in_loop_lea_U0_prototypeCounter_V_d0.read();
}

void dataflow_parent_loop_1::thread_prototypeCounter_V_d1() {
    prototypeCounter_V_d1 = ap_const_lv32_0;
}

void dataflow_parent_loop_1::thread_prototypeCounter_V_we0() {
    prototypeCounter_V_we0 = dataflow_in_loop_lea_U0_prototypeCounter_V_we0.read();
}

void dataflow_parent_loop_1::thread_prototypeCounter_V_we1() {
    prototypeCounter_V_we1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_prototype_V_address0() {
    prototype_V_address0 = dataflow_in_loop_lea_U0_prototype_V_address0.read();
}

void dataflow_parent_loop_1::thread_prototype_V_address1() {
    prototype_V_address1 = ap_const_lv12_0;
}

void dataflow_parent_loop_1::thread_prototype_V_ce0() {
    prototype_V_ce0 = dataflow_in_loop_lea_U0_prototype_V_ce0.read();
}

void dataflow_parent_loop_1::thread_prototype_V_ce1() {
    prototype_V_ce1 = ap_const_logic_0;
}

void dataflow_parent_loop_1::thread_prototype_V_d0() {
    prototype_V_d0 = dataflow_in_loop_lea_U0_prototype_V_d0.read();
}

void dataflow_parent_loop_1::thread_prototype_V_d1() {
    prototype_V_d1 = ap_const_lv64_0;
}

void dataflow_parent_loop_1::thread_prototype_V_we0() {
    prototype_V_we0 = dataflow_in_loop_lea_U0_prototype_V_we0.read();
}

void dataflow_parent_loop_1::thread_prototype_V_we1() {
    prototype_V_we1 = ap_const_logic_0;
}

}

