// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _i2_proc_HH_
#define _i2_proc_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "test_mul_mul_5ns_bkb.h"
#include "test_mul_mul_5ns_cud.h"
#include "i2_proc_result_V.h"
#include "i2_proc_sum1_V.h"

namespace ap_rtl {

struct i2_proc : public sc_module {
    // Port declarations 31
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<5> > compute2_V1_address0;
    sc_out< sc_logic > compute2_V1_ce0;
    sc_in< sc_lv<1> > compute2_V1_q0;
    sc_in< sc_lv<5> > p_0510_0_dout;
    sc_in< sc_logic > p_0510_0_empty_n;
    sc_out< sc_logic > p_0510_0_read;
    sc_out< sc_lv<5> > compute1_V_address0;
    sc_out< sc_logic > compute1_V_ce0;
    sc_out< sc_logic > compute1_V_we0;
    sc_out< sc_lv<32> > compute1_V_d0;
    sc_in< sc_lv<64> > match2_dout;
    sc_in< sc_logic > match2_empty_n;
    sc_out< sc_logic > match2_read;
    sc_out< sc_lv<18> > hcl_rdv3_V_address0;
    sc_out< sc_logic > hcl_rdv3_V_ce0;
    sc_in< sc_lv<64> > hcl_rdv3_V_q0;
    sc_out< sc_lv<12> > prototype_V_address0;
    sc_out< sc_logic > prototype_V_ce0;
    sc_out< sc_lv<8> > prototype_V_we0;
    sc_out< sc_lv<64> > prototype_V_d0;
    sc_out< sc_lv<18> > prototypeCounter_V_address0;
    sc_out< sc_logic > prototypeCounter_V_ce0;
    sc_out< sc_logic > prototypeCounter_V_we0;
    sc_out< sc_lv<32> > prototypeCounter_V_d0;


    // Module declarations
    i2_proc(sc_module_name name);
    SC_HAS_PROCESS(i2_proc);

    ~i2_proc();

    sc_trace_file* mVcdFile;

    i2_proc_result_V* result_V_U;
    i2_proc_sum1_V* sum1_V_U;
    test_mul_mul_5ns_bkb<1,1,5,15,20>* test_mul_mul_5ns_bkb_U7;
    test_mul_mul_5ns_cud<1,1,5,15,18>* test_mul_mul_5ns_cud_U8;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > p_0510_0_blk_n;
    sc_signal< sc_logic > match2_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > icmp_ln887_31_fu_439_p2;
    sc_signal< sc_lv<5> > p_0510_0_read_reg_686;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<5> > compute1_V_addr_reg_698;
    sc_signal< sc_lv<20> > mul_ln791_fu_674_p2;
    sc_signal< sc_lv<20> > mul_ln791_reg_703;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<13> > mul_ln821_fu_394_p2;
    sc_signal< sc_lv<13> > mul_ln821_reg_708;
    sc_signal< sc_lv<1> > compute2_V1_load_reg_713;
    sc_signal< sc_lv<32> > compute1_temp_V_fu_400_p1;
    sc_signal< sc_lv<32> > compute1_temp_V_reg_717;
    sc_signal< sc_lv<18> > mul_ln1371_fu_680_p2;
    sc_signal< sc_lv<18> > mul_ln1371_reg_722;
    sc_signal< sc_lv<32> > zext_ln887_fu_407_p1;
    sc_signal< sc_lv<32> > zext_ln887_reg_727;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<7> > i2_V_fu_417_p2;
    sc_signal< sc_lv<7> > i2_V_reg_737;
    sc_signal< sc_lv<8> > y3_V_fu_429_p2;
    sc_signal< sc_lv<8> > y3_V_reg_745;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<64> > zext_ln544_22_fu_435_p1;
    sc_signal< sc_lv<64> > zext_ln544_22_reg_750;
    sc_signal< sc_lv<1> > icmp_ln887_29_fu_423_p2;
    sc_signal< sc_lv<13> > r_V_fu_445_p2;
    sc_signal< bool > ap_block_state5;
    sc_signal< sc_lv<13> > sum_V_fu_462_p2;
    sc_signal< sc_lv<8> > x6_V_fu_474_p2;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<8> > x7_V_fu_491_p2;
    sc_signal< sc_lv<8> > x7_V_reg_779;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<64> > zext_ln544_25_fu_497_p1;
    sc_signal< sc_lv<64> > zext_ln544_25_reg_784;
    sc_signal< sc_lv<1> > icmp_ln887_33_fu_485_p2;
    sc_signal< sc_lv<8> > x8_V_fu_530_p2;
    sc_signal< sc_lv<8> > x8_V_reg_802;
    sc_signal< sc_lv<64> > zext_ln544_24_fu_536_p1;
    sc_signal< sc_lv<64> > zext_ln544_24_reg_807;
    sc_signal< sc_lv<1> > icmp_ln887_32_fu_524_p2;
    sc_signal< sc_lv<14> > zext_ln81_fu_541_p1;
    sc_signal< sc_lv<14> > zext_ln81_reg_817;
    sc_signal< sc_lv<8> > i3_V_fu_584_p2;
    sc_signal< sc_lv<8> > i3_V_reg_825;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<13> > add_ln821_fu_600_p2;
    sc_signal< sc_lv<13> > add_ln821_reg_830;
    sc_signal< sc_lv<1> > icmp_ln887_36_fu_578_p2;
    sc_signal< sc_lv<4> > tmp_37_reg_840;
    sc_signal< sc_lv<18> > ret_V_8_fu_632_p2;
    sc_signal< sc_lv<18> > ret_V_8_reg_845;
    sc_signal< sc_lv<8> > result_V_address0;
    sc_signal< sc_logic > result_V_ce0;
    sc_signal< sc_logic > result_V_we0;
    sc_signal< sc_lv<13> > result_V_q0;
    sc_signal< sc_lv<8> > sum1_V_address0;
    sc_signal< sc_logic > sum1_V_ce0;
    sc_signal< sc_logic > sum1_V_we0;
    sc_signal< sc_lv<1> > sum1_V_d0;
    sc_signal< sc_lv<1> > sum1_V_q0;
    sc_signal< sc_lv<7> > bvh_d_index_reg_292;
    sc_signal< sc_lv<8> > p_0688_0_i_i_reg_304;
    sc_signal< sc_lv<1> > icmp_ln887_fu_411_p2;
    sc_signal< sc_lv<13> > p_0757_4_i_i_reg_315;
    sc_signal< sc_lv<13> > p_0652_0_i_i_reg_327;
    sc_signal< sc_lv<8> > p_0734_0_i_i_reg_338;
    sc_signal< sc_lv<1> > icmp_ln887_30_fu_468_p2;
    sc_signal< sc_lv<8> > p_0856_0_i_i_reg_349;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<8> > p_0895_0_i_i_reg_360;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<8> > p_0982_0_i_i_reg_371;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<64> > zext_ln544_fu_382_p1;
    sc_signal< sc_lv<64> > zext_ln544_23_fu_480_p1;
    sc_signal< sc_lv<64> > zext_ln791_4_fu_519_p1;
    sc_signal< sc_lv<64> > zext_ln544_26_fu_590_p1;
    sc_signal< sc_lv<64> > sext_ln821_fu_637_p1;
    sc_signal< sc_lv<64> > zext_ln180_1_fu_665_p1;
    sc_signal< sc_lv<1> > icmp_ln887_35_fu_564_p2;
    sc_signal< sc_lv<1> > icmp_ln887_34_fu_571_p2;
    sc_signal< sc_lv<8> > shl_ln821_fu_658_p2;
    sc_signal< sc_lv<5> > mul_ln821_fu_394_p0;
    sc_signal< sc_lv<1> > p_Result_s_fu_451_p3;
    sc_signal< sc_lv<13> > zext_ln68_fu_458_p1;
    sc_signal< sc_lv<12> > tmp_fu_502_p4;
    sc_signal< sc_lv<20> > tmp_35_fu_511_p3;
    sc_signal< sc_lv<1> > p_Result_5_fu_549_p3;
    sc_signal< sc_lv<14> > zext_ln786_fu_545_p1;
    sc_signal< sc_lv<14> > select_ln887_fu_556_p3;
    sc_signal< sc_lv<13> > zext_ln821_fu_596_p1;
    sc_signal< sc_lv<14> > shl_ln_fu_615_p3;
    sc_signal< sc_lv<14> > ret_V_fu_623_p2;
    sc_signal< sc_lv<18> > zext_ln215_fu_628_p1;
    sc_signal< sc_lv<64> > p_Repl2_s_fu_641_p1;
    sc_signal< sc_lv<8> > zext_ln821_8_fu_655_p1;
    sc_signal< sc_lv<5> > mul_ln791_fu_674_p0;
    sc_signal< sc_lv<15> > mul_ln791_fu_674_p1;
    sc_signal< sc_lv<5> > mul_ln1371_fu_680_p0;
    sc_signal< sc_lv<15> > mul_ln1371_fu_680_p1;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    sc_signal< sc_lv<18> > mul_ln1371_fu_680_p00;
    sc_signal< sc_lv<20> > mul_ln791_fu_674_p00;
    sc_signal< sc_lv<13> > mul_ln821_fu_394_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_fsm_state1;
    static const sc_lv<11> ap_ST_fsm_state2;
    static const sc_lv<11> ap_ST_fsm_state3;
    static const sc_lv<11> ap_ST_fsm_state4;
    static const sc_lv<11> ap_ST_fsm_state5;
    static const sc_lv<11> ap_ST_fsm_state6;
    static const sc_lv<11> ap_ST_fsm_state7;
    static const sc_lv<11> ap_ST_fsm_state8;
    static const sc_lv<11> ap_ST_fsm_state9;
    static const sc_lv<11> ap_ST_fsm_state10;
    static const sc_lv<11> ap_ST_fsm_state11;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<13> ap_const_lv13_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<13> ap_const_lv13_9C;
    static const sc_lv<7> ap_const_lv7_40;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<8> ap_const_lv8_9C;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<13> ap_const_lv13_185E;
    static const sc_lv<13> ap_const_lv13_1;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<14> ap_const_lv14_3FFF;
    static const sc_lv<14> ap_const_lv14_0;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<20> ap_const_lv20_2700;
    static const sc_lv<18> ap_const_lv18_2700;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln821_fu_600_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state1();
    void thread_ap_block_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_compute1_V_address0();
    void thread_compute1_V_ce0();
    void thread_compute1_V_d0();
    void thread_compute1_V_we0();
    void thread_compute1_temp_V_fu_400_p1();
    void thread_compute2_V1_address0();
    void thread_compute2_V1_ce0();
    void thread_hcl_rdv3_V_address0();
    void thread_hcl_rdv3_V_ce0();
    void thread_i2_V_fu_417_p2();
    void thread_i3_V_fu_584_p2();
    void thread_icmp_ln887_29_fu_423_p2();
    void thread_icmp_ln887_30_fu_468_p2();
    void thread_icmp_ln887_31_fu_439_p2();
    void thread_icmp_ln887_32_fu_524_p2();
    void thread_icmp_ln887_33_fu_485_p2();
    void thread_icmp_ln887_34_fu_571_p2();
    void thread_icmp_ln887_35_fu_564_p2();
    void thread_icmp_ln887_36_fu_578_p2();
    void thread_icmp_ln887_fu_411_p2();
    void thread_match2_blk_n();
    void thread_match2_read();
    void thread_mul_ln1371_fu_680_p0();
    void thread_mul_ln1371_fu_680_p00();
    void thread_mul_ln1371_fu_680_p1();
    void thread_mul_ln791_fu_674_p0();
    void thread_mul_ln791_fu_674_p00();
    void thread_mul_ln791_fu_674_p1();
    void thread_mul_ln821_fu_394_p0();
    void thread_mul_ln821_fu_394_p00();
    void thread_mul_ln821_fu_394_p2();
    void thread_p_0510_0_blk_n();
    void thread_p_0510_0_read();
    void thread_p_Repl2_s_fu_641_p1();
    void thread_p_Result_5_fu_549_p3();
    void thread_p_Result_s_fu_451_p3();
    void thread_prototypeCounter_V_address0();
    void thread_prototypeCounter_V_ce0();
    void thread_prototypeCounter_V_d0();
    void thread_prototypeCounter_V_we0();
    void thread_prototype_V_address0();
    void thread_prototype_V_ce0();
    void thread_prototype_V_d0();
    void thread_prototype_V_we0();
    void thread_r_V_fu_445_p2();
    void thread_result_V_address0();
    void thread_result_V_ce0();
    void thread_result_V_we0();
    void thread_ret_V_8_fu_632_p2();
    void thread_ret_V_fu_623_p2();
    void thread_select_ln887_fu_556_p3();
    void thread_sext_ln821_fu_637_p1();
    void thread_shl_ln821_fu_658_p2();
    void thread_shl_ln_fu_615_p3();
    void thread_sum1_V_address0();
    void thread_sum1_V_ce0();
    void thread_sum1_V_d0();
    void thread_sum1_V_we0();
    void thread_sum_V_fu_462_p2();
    void thread_tmp_35_fu_511_p3();
    void thread_tmp_fu_502_p4();
    void thread_x6_V_fu_474_p2();
    void thread_x7_V_fu_491_p2();
    void thread_x8_V_fu_530_p2();
    void thread_y3_V_fu_429_p2();
    void thread_zext_ln180_1_fu_665_p1();
    void thread_zext_ln215_fu_628_p1();
    void thread_zext_ln544_22_fu_435_p1();
    void thread_zext_ln544_23_fu_480_p1();
    void thread_zext_ln544_24_fu_536_p1();
    void thread_zext_ln544_25_fu_497_p1();
    void thread_zext_ln544_26_fu_590_p1();
    void thread_zext_ln544_fu_382_p1();
    void thread_zext_ln68_fu_458_p1();
    void thread_zext_ln786_fu_545_p1();
    void thread_zext_ln791_4_fu_519_p1();
    void thread_zext_ln81_fu_541_p1();
    void thread_zext_ln821_8_fu_655_p1();
    void thread_zext_ln821_fu_596_p1();
    void thread_zext_ln887_fu_407_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
