// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "i2_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic i2_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic i2_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> i2_proc::ap_ST_fsm_state1 = "1";
const sc_lv<11> i2_proc::ap_ST_fsm_state2 = "10";
const sc_lv<11> i2_proc::ap_ST_fsm_state3 = "100";
const sc_lv<11> i2_proc::ap_ST_fsm_state4 = "1000";
const sc_lv<11> i2_proc::ap_ST_fsm_state5 = "10000";
const sc_lv<11> i2_proc::ap_ST_fsm_state6 = "100000";
const sc_lv<11> i2_proc::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> i2_proc::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> i2_proc::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> i2_proc::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> i2_proc::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> i2_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> i2_proc::ap_const_lv32_4 = "100";
const sc_lv<1> i2_proc::ap_const_lv1_0 = "0";
const sc_lv<32> i2_proc::ap_const_lv32_1 = "1";
const sc_lv<32> i2_proc::ap_const_lv32_2 = "10";
const sc_lv<32> i2_proc::ap_const_lv32_3 = "11";
const sc_lv<32> i2_proc::ap_const_lv32_5 = "101";
const sc_lv<32> i2_proc::ap_const_lv32_6 = "110";
const sc_lv<1> i2_proc::ap_const_lv1_1 = "1";
const sc_lv<32> i2_proc::ap_const_lv32_9 = "1001";
const sc_lv<7> i2_proc::ap_const_lv7_0 = "0000000";
const sc_lv<8> i2_proc::ap_const_lv8_0 = "00000000";
const sc_lv<13> i2_proc::ap_const_lv13_0 = "0000000000000";
const sc_lv<32> i2_proc::ap_const_lv32_7 = "111";
const sc_lv<32> i2_proc::ap_const_lv32_8 = "1000";
const sc_lv<32> i2_proc::ap_const_lv32_A = "1010";
const sc_lv<13> i2_proc::ap_const_lv13_9C = "10011100";
const sc_lv<7> i2_proc::ap_const_lv7_40 = "1000000";
const sc_lv<7> i2_proc::ap_const_lv7_1 = "1";
const sc_lv<8> i2_proc::ap_const_lv8_9C = "10011100";
const sc_lv<8> i2_proc::ap_const_lv8_1 = "1";
const sc_lv<13> i2_proc::ap_const_lv13_185E = "1100001011110";
const sc_lv<13> i2_proc::ap_const_lv13_1 = "1";
const sc_lv<32> i2_proc::ap_const_lv32_13 = "10011";
const sc_lv<14> i2_proc::ap_const_lv14_3FFF = "11111111111111";
const sc_lv<14> i2_proc::ap_const_lv14_0 = "00000000000000";
const sc_lv<6> i2_proc::ap_const_lv6_0 = "000000";
const sc_lv<64> i2_proc::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<8> i2_proc::ap_const_lv8_FF = "11111111";
const sc_lv<20> i2_proc::ap_const_lv20_2700 = "10011100000000";
const sc_lv<18> i2_proc::ap_const_lv18_2700 = "10011100000000";
const bool i2_proc::ap_const_boolean_1 = true;

i2_proc::i2_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    result_V_U = new i2_proc_result_V("result_V_U");
    result_V_U->clk(ap_clk);
    result_V_U->reset(ap_rst);
    result_V_U->address0(result_V_address0);
    result_V_U->ce0(result_V_ce0);
    result_V_U->we0(result_V_we0);
    result_V_U->d0(p_0757_4_i_i_reg_315);
    result_V_U->q0(result_V_q0);
    sum1_V_U = new i2_proc_sum1_V("sum1_V_U");
    sum1_V_U->clk(ap_clk);
    sum1_V_U->reset(ap_rst);
    sum1_V_U->address0(sum1_V_address0);
    sum1_V_U->ce0(sum1_V_ce0);
    sum1_V_U->we0(sum1_V_we0);
    sum1_V_U->d0(sum1_V_d0);
    sum1_V_U->q0(sum1_V_q0);
    test_mul_mul_5ns_bkb_U7 = new test_mul_mul_5ns_bkb<1,1,5,15,20>("test_mul_mul_5ns_bkb_U7");
    test_mul_mul_5ns_bkb_U7->din0(mul_ln791_fu_674_p0);
    test_mul_mul_5ns_bkb_U7->din1(mul_ln791_fu_674_p1);
    test_mul_mul_5ns_bkb_U7->dout(mul_ln791_fu_674_p2);
    test_mul_mul_5ns_cud_U8 = new test_mul_mul_5ns_cud<1,1,5,15,18>("test_mul_mul_5ns_cud_U8");
    test_mul_mul_5ns_cud_U8->din0(mul_ln1371_fu_680_p0);
    test_mul_mul_5ns_cud_U8->din1(mul_ln1371_fu_680_p1);
    test_mul_mul_5ns_cud_U8->dout(mul_ln1371_fu_680_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln821_fu_600_p2);
    sensitive << ( mul_ln821_reg_708 );
    sensitive << ( zext_ln821_fu_596_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( p_0510_0_empty_n );

    SC_METHOD(thread_ap_block_state5);
    sensitive << ( match2_empty_n );
    sensitive << ( icmp_ln887_31_fu_439_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln887_fu_411_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln887_fu_411_p2 );

    SC_METHOD(thread_compute1_V_address0);
    sensitive << ( compute1_V_addr_reg_698 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_compute1_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_compute1_V_d0);
    sensitive << ( compute1_temp_V_reg_717 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_compute1_V_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln887_30_fu_468_p2 );

    SC_METHOD(thread_compute1_temp_V_fu_400_p1);
    sensitive << ( compute2_V1_q0 );

    SC_METHOD(thread_compute2_V1_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( zext_ln544_fu_382_p1 );

    SC_METHOD(thread_compute2_V1_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_0510_0_empty_n );

    SC_METHOD(thread_hcl_rdv3_V_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln791_4_fu_519_p1 );

    SC_METHOD(thread_hcl_rdv3_V_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_i2_V_fu_417_p2);
    sensitive << ( bvh_d_index_reg_292 );

    SC_METHOD(thread_i3_V_fu_584_p2);
    sensitive << ( p_0982_0_i_i_reg_371 );

    SC_METHOD(thread_icmp_ln887_29_fu_423_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_0688_0_i_i_reg_304 );

    SC_METHOD(thread_icmp_ln887_30_fu_468_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( p_0734_0_i_i_reg_338 );

    SC_METHOD(thread_icmp_ln887_31_fu_439_p2);
    sensitive << ( match2_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln887_31_fu_439_p2 );
    sensitive << ( p_0652_0_i_i_reg_327 );

    SC_METHOD(thread_icmp_ln887_32_fu_524_p2);
    sensitive << ( compute2_V1_load_reg_713 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_0895_0_i_i_reg_360 );

    SC_METHOD(thread_icmp_ln887_33_fu_485_p2);
    sensitive << ( compute2_V1_load_reg_713 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_0856_0_i_i_reg_349 );

    SC_METHOD(thread_icmp_ln887_34_fu_571_p2);
    sensitive << ( result_V_q0 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_icmp_ln887_35_fu_564_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln786_fu_545_p1 );
    sensitive << ( select_ln887_fu_556_p3 );

    SC_METHOD(thread_icmp_ln887_36_fu_578_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( p_0982_0_i_i_reg_371 );

    SC_METHOD(thread_icmp_ln887_fu_411_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( bvh_d_index_reg_292 );

    SC_METHOD(thread_match2_blk_n);
    sensitive << ( match2_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln887_31_fu_439_p2 );

    SC_METHOD(thread_match2_read);
    sensitive << ( match2_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln887_31_fu_439_p2 );

    SC_METHOD(thread_mul_ln1371_fu_680_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mul_ln1371_fu_680_p00 );

    SC_METHOD(thread_mul_ln1371_fu_680_p00);
    sensitive << ( p_0510_0_read_reg_686 );

    SC_METHOD(thread_mul_ln1371_fu_680_p1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_mul_ln791_fu_674_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mul_ln791_fu_674_p00 );

    SC_METHOD(thread_mul_ln791_fu_674_p00);
    sensitive << ( p_0510_0_read_reg_686 );

    SC_METHOD(thread_mul_ln791_fu_674_p1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_mul_ln821_fu_394_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mul_ln821_fu_394_p00 );

    SC_METHOD(thread_mul_ln821_fu_394_p00);
    sensitive << ( p_0510_0_read_reg_686 );

    SC_METHOD(thread_mul_ln821_fu_394_p2);
    sensitive << ( mul_ln821_fu_394_p0 );

    SC_METHOD(thread_p_0510_0_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_0510_0_empty_n );

    SC_METHOD(thread_p_0510_0_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_0510_0_empty_n );

    SC_METHOD(thread_p_Repl2_s_fu_641_p1);
    sensitive << ( sum1_V_q0 );

    SC_METHOD(thread_p_Result_5_fu_549_p3);
    sensitive << ( hcl_rdv3_V_q0 );
    sensitive << ( zext_ln887_reg_727 );

    SC_METHOD(thread_p_Result_s_fu_451_p3);
    sensitive << ( match2_dout );
    sensitive << ( zext_ln887_reg_727 );

    SC_METHOD(thread_prototypeCounter_V_address0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( zext_ln180_1_fu_665_p1 );

    SC_METHOD(thread_prototypeCounter_V_ce0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_prototypeCounter_V_d0);
    sensitive << ( result_V_q0 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_prototypeCounter_V_we0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_prototype_V_address0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( sext_ln821_fu_637_p1 );

    SC_METHOD(thread_prototype_V_ce0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_prototype_V_d0);
    sensitive << ( zext_ln887_reg_727 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( p_Repl2_s_fu_641_p1 );

    SC_METHOD(thread_prototype_V_we0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( shl_ln821_fu_658_p2 );

    SC_METHOD(thread_r_V_fu_445_p2);
    sensitive << ( p_0652_0_i_i_reg_327 );

    SC_METHOD(thread_result_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( compute2_V1_load_reg_713 );
    sensitive << ( zext_ln544_22_reg_750 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln544_25_fu_497_p1 );
    sensitive << ( icmp_ln887_33_fu_485_p2 );
    sensitive << ( zext_ln544_24_fu_536_p1 );
    sensitive << ( icmp_ln887_32_fu_524_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( zext_ln544_26_fu_590_p1 );

    SC_METHOD(thread_result_V_ce0);
    sensitive << ( match2_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln887_31_fu_439_p2 );
    sensitive << ( compute2_V1_load_reg_713 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln887_33_fu_485_p2 );
    sensitive << ( icmp_ln887_32_fu_524_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_result_V_we0);
    sensitive << ( match2_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln887_31_fu_439_p2 );

    SC_METHOD(thread_ret_V_8_fu_632_p2);
    sensitive << ( mul_ln1371_reg_722 );
    sensitive << ( zext_ln215_fu_628_p1 );

    SC_METHOD(thread_ret_V_fu_623_p2);
    sensitive << ( zext_ln81_reg_817 );
    sensitive << ( shl_ln_fu_615_p3 );

    SC_METHOD(thread_select_ln887_fu_556_p3);
    sensitive << ( p_Result_5_fu_549_p3 );

    SC_METHOD(thread_sext_ln821_fu_637_p1);
    sensitive << ( add_ln821_reg_830 );

    SC_METHOD(thread_shl_ln821_fu_658_p2);
    sensitive << ( zext_ln821_8_fu_655_p1 );

    SC_METHOD(thread_shl_ln_fu_615_p3);
    sensitive << ( p_0982_0_i_i_reg_371 );

    SC_METHOD(thread_sum1_V_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln544_25_reg_784 );
    sensitive << ( zext_ln544_24_reg_807 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln544_23_fu_480_p1 );
    sensitive << ( zext_ln544_26_fu_590_p1 );

    SC_METHOD(thread_sum1_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_sum1_V_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln887_35_fu_564_p2 );
    sensitive << ( icmp_ln887_34_fu_571_p2 );

    SC_METHOD(thread_sum1_V_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln887_30_fu_468_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_sum_V_fu_462_p2);
    sensitive << ( p_0757_4_i_i_reg_315 );
    sensitive << ( zext_ln68_fu_458_p1 );

    SC_METHOD(thread_tmp_35_fu_511_p3);
    sensitive << ( p_0856_0_i_i_reg_349 );
    sensitive << ( tmp_fu_502_p4 );

    SC_METHOD(thread_tmp_fu_502_p4);
    sensitive << ( mul_ln791_reg_703 );

    SC_METHOD(thread_x6_V_fu_474_p2);
    sensitive << ( p_0734_0_i_i_reg_338 );

    SC_METHOD(thread_x7_V_fu_491_p2);
    sensitive << ( p_0856_0_i_i_reg_349 );

    SC_METHOD(thread_x8_V_fu_530_p2);
    sensitive << ( p_0895_0_i_i_reg_360 );

    SC_METHOD(thread_y3_V_fu_429_p2);
    sensitive << ( p_0688_0_i_i_reg_304 );

    SC_METHOD(thread_zext_ln180_1_fu_665_p1);
    sensitive << ( ret_V_8_reg_845 );

    SC_METHOD(thread_zext_ln215_fu_628_p1);
    sensitive << ( ret_V_fu_623_p2 );

    SC_METHOD(thread_zext_ln544_22_fu_435_p1);
    sensitive << ( p_0688_0_i_i_reg_304 );

    SC_METHOD(thread_zext_ln544_23_fu_480_p1);
    sensitive << ( p_0734_0_i_i_reg_338 );

    SC_METHOD(thread_zext_ln544_24_fu_536_p1);
    sensitive << ( p_0895_0_i_i_reg_360 );

    SC_METHOD(thread_zext_ln544_25_fu_497_p1);
    sensitive << ( p_0856_0_i_i_reg_349 );

    SC_METHOD(thread_zext_ln544_26_fu_590_p1);
    sensitive << ( p_0982_0_i_i_reg_371 );

    SC_METHOD(thread_zext_ln544_fu_382_p1);
    sensitive << ( p_0510_0_dout );

    SC_METHOD(thread_zext_ln68_fu_458_p1);
    sensitive << ( p_Result_s_fu_451_p3 );

    SC_METHOD(thread_zext_ln786_fu_545_p1);
    sensitive << ( result_V_q0 );

    SC_METHOD(thread_zext_ln791_4_fu_519_p1);
    sensitive << ( tmp_35_fu_511_p3 );

    SC_METHOD(thread_zext_ln81_fu_541_p1);
    sensitive << ( bvh_d_index_reg_292 );

    SC_METHOD(thread_zext_ln821_8_fu_655_p1);
    sensitive << ( tmp_37_reg_840 );

    SC_METHOD(thread_zext_ln821_fu_596_p1);
    sensitive << ( p_0982_0_i_i_reg_371 );

    SC_METHOD(thread_zext_ln887_fu_407_p1);
    sensitive << ( bvh_d_index_reg_292 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_0510_0_empty_n );
    sensitive << ( match2_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln887_31_fu_439_p2 );
    sensitive << ( compute2_V1_load_reg_713 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln887_29_fu_423_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln887_33_fu_485_p2 );
    sensitive << ( icmp_ln887_32_fu_524_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln887_36_fu_578_p2 );
    sensitive << ( icmp_ln887_fu_411_p2 );
    sensitive << ( icmp_ln887_30_fu_468_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "i2_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, compute2_V1_address0, "(port)compute2_V1_address0");
    sc_trace(mVcdFile, compute2_V1_ce0, "(port)compute2_V1_ce0");
    sc_trace(mVcdFile, compute2_V1_q0, "(port)compute2_V1_q0");
    sc_trace(mVcdFile, p_0510_0_dout, "(port)p_0510_0_dout");
    sc_trace(mVcdFile, p_0510_0_empty_n, "(port)p_0510_0_empty_n");
    sc_trace(mVcdFile, p_0510_0_read, "(port)p_0510_0_read");
    sc_trace(mVcdFile, compute1_V_address0, "(port)compute1_V_address0");
    sc_trace(mVcdFile, compute1_V_ce0, "(port)compute1_V_ce0");
    sc_trace(mVcdFile, compute1_V_we0, "(port)compute1_V_we0");
    sc_trace(mVcdFile, compute1_V_d0, "(port)compute1_V_d0");
    sc_trace(mVcdFile, match2_dout, "(port)match2_dout");
    sc_trace(mVcdFile, match2_empty_n, "(port)match2_empty_n");
    sc_trace(mVcdFile, match2_read, "(port)match2_read");
    sc_trace(mVcdFile, hcl_rdv3_V_address0, "(port)hcl_rdv3_V_address0");
    sc_trace(mVcdFile, hcl_rdv3_V_ce0, "(port)hcl_rdv3_V_ce0");
    sc_trace(mVcdFile, hcl_rdv3_V_q0, "(port)hcl_rdv3_V_q0");
    sc_trace(mVcdFile, prototype_V_address0, "(port)prototype_V_address0");
    sc_trace(mVcdFile, prototype_V_ce0, "(port)prototype_V_ce0");
    sc_trace(mVcdFile, prototype_V_we0, "(port)prototype_V_we0");
    sc_trace(mVcdFile, prototype_V_d0, "(port)prototype_V_d0");
    sc_trace(mVcdFile, prototypeCounter_V_address0, "(port)prototypeCounter_V_address0");
    sc_trace(mVcdFile, prototypeCounter_V_ce0, "(port)prototypeCounter_V_ce0");
    sc_trace(mVcdFile, prototypeCounter_V_we0, "(port)prototypeCounter_V_we0");
    sc_trace(mVcdFile, prototypeCounter_V_d0, "(port)prototypeCounter_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_0510_0_blk_n, "p_0510_0_blk_n");
    sc_trace(mVcdFile, match2_blk_n, "match2_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln887_31_fu_439_p2, "icmp_ln887_31_fu_439_p2");
    sc_trace(mVcdFile, p_0510_0_read_reg_686, "p_0510_0_read_reg_686");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, compute1_V_addr_reg_698, "compute1_V_addr_reg_698");
    sc_trace(mVcdFile, mul_ln791_fu_674_p2, "mul_ln791_fu_674_p2");
    sc_trace(mVcdFile, mul_ln791_reg_703, "mul_ln791_reg_703");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, mul_ln821_fu_394_p2, "mul_ln821_fu_394_p2");
    sc_trace(mVcdFile, mul_ln821_reg_708, "mul_ln821_reg_708");
    sc_trace(mVcdFile, compute2_V1_load_reg_713, "compute2_V1_load_reg_713");
    sc_trace(mVcdFile, compute1_temp_V_fu_400_p1, "compute1_temp_V_fu_400_p1");
    sc_trace(mVcdFile, compute1_temp_V_reg_717, "compute1_temp_V_reg_717");
    sc_trace(mVcdFile, mul_ln1371_fu_680_p2, "mul_ln1371_fu_680_p2");
    sc_trace(mVcdFile, mul_ln1371_reg_722, "mul_ln1371_reg_722");
    sc_trace(mVcdFile, zext_ln887_fu_407_p1, "zext_ln887_fu_407_p1");
    sc_trace(mVcdFile, zext_ln887_reg_727, "zext_ln887_reg_727");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i2_V_fu_417_p2, "i2_V_fu_417_p2");
    sc_trace(mVcdFile, i2_V_reg_737, "i2_V_reg_737");
    sc_trace(mVcdFile, y3_V_fu_429_p2, "y3_V_fu_429_p2");
    sc_trace(mVcdFile, y3_V_reg_745, "y3_V_reg_745");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln544_22_fu_435_p1, "zext_ln544_22_fu_435_p1");
    sc_trace(mVcdFile, zext_ln544_22_reg_750, "zext_ln544_22_reg_750");
    sc_trace(mVcdFile, icmp_ln887_29_fu_423_p2, "icmp_ln887_29_fu_423_p2");
    sc_trace(mVcdFile, r_V_fu_445_p2, "r_V_fu_445_p2");
    sc_trace(mVcdFile, ap_block_state5, "ap_block_state5");
    sc_trace(mVcdFile, sum_V_fu_462_p2, "sum_V_fu_462_p2");
    sc_trace(mVcdFile, x6_V_fu_474_p2, "x6_V_fu_474_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, x7_V_fu_491_p2, "x7_V_fu_491_p2");
    sc_trace(mVcdFile, x7_V_reg_779, "x7_V_reg_779");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, zext_ln544_25_fu_497_p1, "zext_ln544_25_fu_497_p1");
    sc_trace(mVcdFile, zext_ln544_25_reg_784, "zext_ln544_25_reg_784");
    sc_trace(mVcdFile, icmp_ln887_33_fu_485_p2, "icmp_ln887_33_fu_485_p2");
    sc_trace(mVcdFile, x8_V_fu_530_p2, "x8_V_fu_530_p2");
    sc_trace(mVcdFile, x8_V_reg_802, "x8_V_reg_802");
    sc_trace(mVcdFile, zext_ln544_24_fu_536_p1, "zext_ln544_24_fu_536_p1");
    sc_trace(mVcdFile, zext_ln544_24_reg_807, "zext_ln544_24_reg_807");
    sc_trace(mVcdFile, icmp_ln887_32_fu_524_p2, "icmp_ln887_32_fu_524_p2");
    sc_trace(mVcdFile, zext_ln81_fu_541_p1, "zext_ln81_fu_541_p1");
    sc_trace(mVcdFile, zext_ln81_reg_817, "zext_ln81_reg_817");
    sc_trace(mVcdFile, i3_V_fu_584_p2, "i3_V_fu_584_p2");
    sc_trace(mVcdFile, i3_V_reg_825, "i3_V_reg_825");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, add_ln821_fu_600_p2, "add_ln821_fu_600_p2");
    sc_trace(mVcdFile, add_ln821_reg_830, "add_ln821_reg_830");
    sc_trace(mVcdFile, icmp_ln887_36_fu_578_p2, "icmp_ln887_36_fu_578_p2");
    sc_trace(mVcdFile, tmp_37_reg_840, "tmp_37_reg_840");
    sc_trace(mVcdFile, ret_V_8_fu_632_p2, "ret_V_8_fu_632_p2");
    sc_trace(mVcdFile, ret_V_8_reg_845, "ret_V_8_reg_845");
    sc_trace(mVcdFile, result_V_address0, "result_V_address0");
    sc_trace(mVcdFile, result_V_ce0, "result_V_ce0");
    sc_trace(mVcdFile, result_V_we0, "result_V_we0");
    sc_trace(mVcdFile, result_V_q0, "result_V_q0");
    sc_trace(mVcdFile, sum1_V_address0, "sum1_V_address0");
    sc_trace(mVcdFile, sum1_V_ce0, "sum1_V_ce0");
    sc_trace(mVcdFile, sum1_V_we0, "sum1_V_we0");
    sc_trace(mVcdFile, sum1_V_d0, "sum1_V_d0");
    sc_trace(mVcdFile, sum1_V_q0, "sum1_V_q0");
    sc_trace(mVcdFile, bvh_d_index_reg_292, "bvh_d_index_reg_292");
    sc_trace(mVcdFile, p_0688_0_i_i_reg_304, "p_0688_0_i_i_reg_304");
    sc_trace(mVcdFile, icmp_ln887_fu_411_p2, "icmp_ln887_fu_411_p2");
    sc_trace(mVcdFile, p_0757_4_i_i_reg_315, "p_0757_4_i_i_reg_315");
    sc_trace(mVcdFile, p_0652_0_i_i_reg_327, "p_0652_0_i_i_reg_327");
    sc_trace(mVcdFile, p_0734_0_i_i_reg_338, "p_0734_0_i_i_reg_338");
    sc_trace(mVcdFile, icmp_ln887_30_fu_468_p2, "icmp_ln887_30_fu_468_p2");
    sc_trace(mVcdFile, p_0856_0_i_i_reg_349, "p_0856_0_i_i_reg_349");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, p_0895_0_i_i_reg_360, "p_0895_0_i_i_reg_360");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, p_0982_0_i_i_reg_371, "p_0982_0_i_i_reg_371");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, zext_ln544_fu_382_p1, "zext_ln544_fu_382_p1");
    sc_trace(mVcdFile, zext_ln544_23_fu_480_p1, "zext_ln544_23_fu_480_p1");
    sc_trace(mVcdFile, zext_ln791_4_fu_519_p1, "zext_ln791_4_fu_519_p1");
    sc_trace(mVcdFile, zext_ln544_26_fu_590_p1, "zext_ln544_26_fu_590_p1");
    sc_trace(mVcdFile, sext_ln821_fu_637_p1, "sext_ln821_fu_637_p1");
    sc_trace(mVcdFile, zext_ln180_1_fu_665_p1, "zext_ln180_1_fu_665_p1");
    sc_trace(mVcdFile, icmp_ln887_35_fu_564_p2, "icmp_ln887_35_fu_564_p2");
    sc_trace(mVcdFile, icmp_ln887_34_fu_571_p2, "icmp_ln887_34_fu_571_p2");
    sc_trace(mVcdFile, shl_ln821_fu_658_p2, "shl_ln821_fu_658_p2");
    sc_trace(mVcdFile, mul_ln821_fu_394_p0, "mul_ln821_fu_394_p0");
    sc_trace(mVcdFile, p_Result_s_fu_451_p3, "p_Result_s_fu_451_p3");
    sc_trace(mVcdFile, zext_ln68_fu_458_p1, "zext_ln68_fu_458_p1");
    sc_trace(mVcdFile, tmp_fu_502_p4, "tmp_fu_502_p4");
    sc_trace(mVcdFile, tmp_35_fu_511_p3, "tmp_35_fu_511_p3");
    sc_trace(mVcdFile, p_Result_5_fu_549_p3, "p_Result_5_fu_549_p3");
    sc_trace(mVcdFile, zext_ln786_fu_545_p1, "zext_ln786_fu_545_p1");
    sc_trace(mVcdFile, select_ln887_fu_556_p3, "select_ln887_fu_556_p3");
    sc_trace(mVcdFile, zext_ln821_fu_596_p1, "zext_ln821_fu_596_p1");
    sc_trace(mVcdFile, shl_ln_fu_615_p3, "shl_ln_fu_615_p3");
    sc_trace(mVcdFile, ret_V_fu_623_p2, "ret_V_fu_623_p2");
    sc_trace(mVcdFile, zext_ln215_fu_628_p1, "zext_ln215_fu_628_p1");
    sc_trace(mVcdFile, p_Repl2_s_fu_641_p1, "p_Repl2_s_fu_641_p1");
    sc_trace(mVcdFile, zext_ln821_8_fu_655_p1, "zext_ln821_8_fu_655_p1");
    sc_trace(mVcdFile, mul_ln791_fu_674_p0, "mul_ln791_fu_674_p0");
    sc_trace(mVcdFile, mul_ln791_fu_674_p1, "mul_ln791_fu_674_p1");
    sc_trace(mVcdFile, mul_ln1371_fu_680_p0, "mul_ln1371_fu_680_p0");
    sc_trace(mVcdFile, mul_ln1371_fu_680_p1, "mul_ln1371_fu_680_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln1371_fu_680_p00, "mul_ln1371_fu_680_p00");
    sc_trace(mVcdFile, mul_ln791_fu_674_p00, "mul_ln791_fu_674_p00");
    sc_trace(mVcdFile, mul_ln821_fu_394_p00, "mul_ln821_fu_394_p00");
#endif

    }
}

i2_proc::~i2_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete result_V_U;
    delete sum1_V_U;
    delete test_mul_mul_5ns_bkb_U7;
    delete test_mul_mul_5ns_cud_U8;
}

void i2_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_411_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        bvh_d_index_reg_292 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_36_fu_578_p2.read()))) {
        bvh_d_index_reg_292 = i2_V_reg_737.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_29_fu_423_p2.read()))) {
        p_0652_0_i_i_reg_327 = ap_const_lv13_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && 
                !(esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, match2_empty_n.read())))) {
        p_0652_0_i_i_reg_327 = r_V_fu_445_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_fu_411_p2.read()))) {
        p_0688_0_i_i_reg_304 = ap_const_lv8_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                !(esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, match2_empty_n.read())) && 
                esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_1))) {
        p_0688_0_i_i_reg_304 = y3_V_reg_745.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln887_29_fu_423_p2.read(), ap_const_lv1_1))) {
        p_0734_0_i_i_reg_338 = ap_const_lv8_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_30_fu_468_p2.read()))) {
        p_0734_0_i_i_reg_338 = x6_V_fu_474_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_29_fu_423_p2.read()))) {
        p_0757_4_i_i_reg_315 = ap_const_lv13_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && 
                !(esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, match2_empty_n.read())))) {
        p_0757_4_i_i_reg_315 = sum_V_fu_462_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, compute2_V1_load_reg_713.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_30_fu_468_p2.read()))) {
        p_0856_0_i_i_reg_349 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_0856_0_i_i_reg_349 = x7_V_reg_779.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(compute2_V1_load_reg_713.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_30_fu_468_p2.read()))) {
        p_0895_0_i_i_reg_360 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        p_0895_0_i_i_reg_360 = x8_V_reg_802.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        p_0982_0_i_i_reg_371 = i3_V_reg_825.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                ((esl_seteq<1,1,1>(compute2_V1_load_reg_713.read(), ap_const_lv1_1) && 
                  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_32_fu_524_p2.read())) || 
                 (esl_seteq<1,1,1>(ap_const_lv1_0, compute2_V1_load_reg_713.read()) && 
                  esl_seteq<1,1,1>(icmp_ln887_33_fu_485_p2.read(), ap_const_lv1_1))))) {
        p_0982_0_i_i_reg_371 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_36_fu_578_p2.read()))) {
        add_ln821_reg_830 = add_ln821_fu_600_p2.read();
        ret_V_8_reg_845 = ret_V_8_fu_632_p2.read();
        tmp_37_reg_840 = bvh_d_index_reg_292.read().range(6, 3);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_0510_0_empty_n.read())))) {
        compute1_V_addr_reg_698 =  (sc_lv<5>) (zext_ln544_fu_382_p1.read());
        p_0510_0_read_reg_686 = p_0510_0_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        compute1_temp_V_reg_717 = compute1_temp_V_fu_400_p1.read();
        compute2_V1_load_reg_713 = compute2_V1_q0.read();
        mul_ln1371_reg_722 = mul_ln1371_fu_680_p2.read();
        mul_ln791_reg_703 = mul_ln791_fu_674_p2.read();
        mul_ln821_reg_708 = mul_ln821_fu_394_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i2_V_reg_737 = i2_V_fu_417_p2.read();
        zext_ln887_reg_727 = zext_ln887_fu_407_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i3_V_reg_825 = i3_V_fu_584_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, compute2_V1_load_reg_713.read()))) {
        x7_V_reg_779 = x7_V_fu_491_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(compute2_V1_load_reg_713.read(), ap_const_lv1_1))) {
        x8_V_reg_802 = x8_V_fu_530_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        y3_V_reg_745 = y3_V_fu_429_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_29_fu_423_p2.read()))) {
        zext_ln544_22_reg_750 = zext_ln544_22_fu_435_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(compute2_V1_load_reg_713.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_32_fu_524_p2.read()))) {
        zext_ln544_24_reg_807 = zext_ln544_24_fu_536_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, compute2_V1_load_reg_713.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_33_fu_485_p2.read()))) {
        zext_ln544_25_reg_784 = zext_ln544_25_fu_497_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && ((esl_seteq<1,1,1>(compute2_V1_load_reg_713.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_32_fu_524_p2.read())) || 
  (esl_seteq<1,1,1>(ap_const_lv1_0, compute2_V1_load_reg_713.read()) && 
   esl_seteq<1,1,1>(icmp_ln887_33_fu_485_p2.read(), ap_const_lv1_1))))) {
        zext_ln81_reg_817 = zext_ln81_fu_541_p1.read();
    }
}

void i2_proc::thread_add_ln821_fu_600_p2() {
    add_ln821_fu_600_p2 = (!zext_ln821_fu_596_p1.read().is_01() || !mul_ln821_reg_708.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln821_fu_596_p1.read()) + sc_biguint<13>(mul_ln821_reg_708.read()));
}

void i2_proc::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void i2_proc::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void i2_proc::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void i2_proc::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void i2_proc::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void i2_proc::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void i2_proc::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void i2_proc::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void i2_proc::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void i2_proc::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void i2_proc::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void i2_proc::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_0510_0_empty_n.read()));
}

void i2_proc::thread_ap_block_state5() {
    ap_block_state5 = (esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, match2_empty_n.read()));
}

void i2_proc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_411_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void i2_proc::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void i2_proc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_411_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void i2_proc::thread_compute1_V_address0() {
    compute1_V_address0 = compute1_V_addr_reg_698.read();
}

void i2_proc::thread_compute1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        compute1_V_ce0 = ap_const_logic_1;
    } else {
        compute1_V_ce0 = ap_const_logic_0;
    }
}

void i2_proc::thread_compute1_V_d0() {
    compute1_V_d0 = compute1_temp_V_reg_717.read();
}

void i2_proc::thread_compute1_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_30_fu_468_p2.read()))) {
        compute1_V_we0 = ap_const_logic_1;
    } else {
        compute1_V_we0 = ap_const_logic_0;
    }
}

void i2_proc::thread_compute1_temp_V_fu_400_p1() {
    compute1_temp_V_fu_400_p1 = esl_zext<32,1>(compute2_V1_q0.read());
}

void i2_proc::thread_compute2_V1_address0() {
    compute2_V1_address0 =  (sc_lv<5>) (zext_ln544_fu_382_p1.read());
}

void i2_proc::thread_compute2_V1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_0510_0_empty_n.read())))) {
        compute2_V1_ce0 = ap_const_logic_1;
    } else {
        compute2_V1_ce0 = ap_const_logic_0;
    }
}

void i2_proc::thread_hcl_rdv3_V_address0() {
    hcl_rdv3_V_address0 =  (sc_lv<18>) (zext_ln791_4_fu_519_p1.read());
}

void i2_proc::thread_hcl_rdv3_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        hcl_rdv3_V_ce0 = ap_const_logic_1;
    } else {
        hcl_rdv3_V_ce0 = ap_const_logic_0;
    }
}

void i2_proc::thread_i2_V_fu_417_p2() {
    i2_V_fu_417_p2 = (!bvh_d_index_reg_292.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(bvh_d_index_reg_292.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void i2_proc::thread_i3_V_fu_584_p2() {
    i3_V_fu_584_p2 = (!p_0982_0_i_i_reg_371.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(p_0982_0_i_i_reg_371.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void i2_proc::thread_icmp_ln887_29_fu_423_p2() {
    icmp_ln887_29_fu_423_p2 = (!p_0688_0_i_i_reg_304.read().is_01() || !ap_const_lv8_9C.is_01())? sc_lv<1>(): sc_lv<1>(p_0688_0_i_i_reg_304.read() == ap_const_lv8_9C);
}

void i2_proc::thread_icmp_ln887_30_fu_468_p2() {
    icmp_ln887_30_fu_468_p2 = (!p_0734_0_i_i_reg_338.read().is_01() || !ap_const_lv8_9C.is_01())? sc_lv<1>(): sc_lv<1>(p_0734_0_i_i_reg_338.read() == ap_const_lv8_9C);
}

void i2_proc::thread_icmp_ln887_31_fu_439_p2() {
    icmp_ln887_31_fu_439_p2 = (!p_0652_0_i_i_reg_327.read().is_01() || !ap_const_lv13_185E.is_01())? sc_lv<1>(): sc_lv<1>(p_0652_0_i_i_reg_327.read() == ap_const_lv13_185E);
}

void i2_proc::thread_icmp_ln887_32_fu_524_p2() {
    icmp_ln887_32_fu_524_p2 = (!p_0895_0_i_i_reg_360.read().is_01() || !ap_const_lv8_9C.is_01())? sc_lv<1>(): sc_lv<1>(p_0895_0_i_i_reg_360.read() == ap_const_lv8_9C);
}

void i2_proc::thread_icmp_ln887_33_fu_485_p2() {
    icmp_ln887_33_fu_485_p2 = (!p_0856_0_i_i_reg_349.read().is_01() || !ap_const_lv8_9C.is_01())? sc_lv<1>(): sc_lv<1>(p_0856_0_i_i_reg_349.read() == ap_const_lv8_9C);
}

void i2_proc::thread_icmp_ln887_34_fu_571_p2() {
    icmp_ln887_34_fu_571_p2 = (!result_V_q0.read().is_01() || !ap_const_lv13_0.is_01())? sc_lv<1>(): sc_lv<1>(result_V_q0.read() != ap_const_lv13_0);
}

void i2_proc::thread_icmp_ln887_35_fu_564_p2() {
    icmp_ln887_35_fu_564_p2 = (!zext_ln786_fu_545_p1.read().is_01() || !select_ln887_fu_556_p3.read().is_01())? sc_lv<1>(): sc_lv<1>(zext_ln786_fu_545_p1.read() != select_ln887_fu_556_p3.read());
}

void i2_proc::thread_icmp_ln887_36_fu_578_p2() {
    icmp_ln887_36_fu_578_p2 = (!p_0982_0_i_i_reg_371.read().is_01() || !ap_const_lv8_9C.is_01())? sc_lv<1>(): sc_lv<1>(p_0982_0_i_i_reg_371.read() == ap_const_lv8_9C);
}

void i2_proc::thread_icmp_ln887_fu_411_p2() {
    icmp_ln887_fu_411_p2 = (!bvh_d_index_reg_292.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(bvh_d_index_reg_292.read() == ap_const_lv7_40);
}

void i2_proc::thread_match2_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0))) {
        match2_blk_n = match2_empty_n.read();
    } else {
        match2_blk_n = ap_const_logic_1;
    }
}

void i2_proc::thread_match2_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, match2_empty_n.read())))) {
        match2_read = ap_const_logic_1;
    } else {
        match2_read = ap_const_logic_0;
    }
}

void i2_proc::thread_mul_ln1371_fu_680_p0() {
    mul_ln1371_fu_680_p0 =  (sc_lv<5>) (mul_ln1371_fu_680_p00.read());
}

void i2_proc::thread_mul_ln1371_fu_680_p00() {
    mul_ln1371_fu_680_p00 = esl_zext<18,5>(p_0510_0_read_reg_686.read());
}

void i2_proc::thread_mul_ln1371_fu_680_p1() {
    mul_ln1371_fu_680_p1 =  (sc_lv<15>) (ap_const_lv18_2700);
}

void i2_proc::thread_mul_ln791_fu_674_p0() {
    mul_ln791_fu_674_p0 =  (sc_lv<5>) (mul_ln791_fu_674_p00.read());
}

void i2_proc::thread_mul_ln791_fu_674_p00() {
    mul_ln791_fu_674_p00 = esl_zext<20,5>(p_0510_0_read_reg_686.read());
}

void i2_proc::thread_mul_ln791_fu_674_p1() {
    mul_ln791_fu_674_p1 =  (sc_lv<15>) (ap_const_lv20_2700);
}

void i2_proc::thread_mul_ln821_fu_394_p0() {
    mul_ln821_fu_394_p0 =  (sc_lv<5>) (mul_ln821_fu_394_p00.read());
}

void i2_proc::thread_mul_ln821_fu_394_p00() {
    mul_ln821_fu_394_p00 = esl_zext<13,5>(p_0510_0_read_reg_686.read());
}

void i2_proc::thread_mul_ln821_fu_394_p2() {
    mul_ln821_fu_394_p2 = (!mul_ln821_fu_394_p0.read().is_01() || !ap_const_lv13_9C.is_01())? sc_lv<13>(): sc_biguint<5>(mul_ln821_fu_394_p0.read()) * sc_biguint<13>(ap_const_lv13_9C);
}

void i2_proc::thread_p_0510_0_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_0510_0_blk_n = p_0510_0_empty_n.read();
    } else {
        p_0510_0_blk_n = ap_const_logic_1;
    }
}

void i2_proc::thread_p_0510_0_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_0510_0_empty_n.read())))) {
        p_0510_0_read = ap_const_logic_1;
    } else {
        p_0510_0_read = ap_const_logic_0;
    }
}

void i2_proc::thread_p_Repl2_s_fu_641_p1() {
    p_Repl2_s_fu_641_p1 = esl_zext<64,1>(sum1_V_q0.read());
}

void i2_proc::thread_p_Result_5_fu_549_p3() {
    p_Result_5_fu_549_p3 = (!zext_ln887_reg_727.read().is_01() || sc_biguint<32>(zext_ln887_reg_727.read()).to_uint() >= 64)? sc_lv<1>(): hcl_rdv3_V_q0.read().range(sc_biguint<32>(zext_ln887_reg_727.read()).to_uint(), sc_biguint<32>(zext_ln887_reg_727.read()).to_uint());
}

void i2_proc::thread_p_Result_s_fu_451_p3() {
    p_Result_s_fu_451_p3 = (!zext_ln887_reg_727.read().is_01() || sc_biguint<32>(zext_ln887_reg_727.read()).to_uint() >= 64)? sc_lv<1>(): match2_dout.read().range(sc_biguint<32>(zext_ln887_reg_727.read()).to_uint(), sc_biguint<32>(zext_ln887_reg_727.read()).to_uint());
}

void i2_proc::thread_prototypeCounter_V_address0() {
    prototypeCounter_V_address0 =  (sc_lv<18>) (zext_ln180_1_fu_665_p1.read());
}

void i2_proc::thread_prototypeCounter_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        prototypeCounter_V_ce0 = ap_const_logic_1;
    } else {
        prototypeCounter_V_ce0 = ap_const_logic_0;
    }
}

void i2_proc::thread_prototypeCounter_V_d0() {
    prototypeCounter_V_d0 = esl_zext<32,13>(result_V_q0.read());
}

void i2_proc::thread_prototypeCounter_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        prototypeCounter_V_we0 = ap_const_logic_1;
    } else {
        prototypeCounter_V_we0 = ap_const_logic_0;
    }
}

void i2_proc::thread_prototype_V_address0() {
    prototype_V_address0 =  (sc_lv<12>) (sext_ln821_fu_637_p1.read());
}

void i2_proc::thread_prototype_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        prototype_V_ce0 = ap_const_logic_1;
    } else {
        prototype_V_ce0 = ap_const_logic_0;
    }
}

void i2_proc::thread_prototype_V_d0() {
    prototype_V_d0 = esl_bitset<64,64,32,64>(ap_const_lv64_0, zext_ln887_reg_727.read(), p_Repl2_s_fu_641_p1.read());
}

void i2_proc::thread_prototype_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        prototype_V_we0 = shl_ln821_fu_658_p2.read();
    } else {
        prototype_V_we0 = ap_const_lv8_0;
    }
}

void i2_proc::thread_r_V_fu_445_p2() {
    r_V_fu_445_p2 = (!p_0652_0_i_i_reg_327.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(p_0652_0_i_i_reg_327.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void i2_proc::thread_result_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        result_V_address0 =  (sc_lv<8>) (zext_ln544_26_fu_590_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(compute2_V1_load_reg_713.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_32_fu_524_p2.read()))) {
        result_V_address0 =  (sc_lv<8>) (zext_ln544_24_fu_536_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, compute2_V1_load_reg_713.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_33_fu_485_p2.read()))) {
        result_V_address0 =  (sc_lv<8>) (zext_ln544_25_fu_497_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        result_V_address0 =  (sc_lv<8>) (zext_ln544_22_reg_750.read());
    } else {
        result_V_address0 = "XXXXXXXX";
    }
}

void i2_proc::thread_result_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          !(esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, match2_empty_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, compute2_V1_load_reg_713.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_33_fu_485_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(compute2_V1_load_reg_713.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_32_fu_524_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        result_V_ce0 = ap_const_logic_1;
    } else {
        result_V_ce0 = ap_const_logic_0;
    }
}

void i2_proc::thread_result_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         !(esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, match2_empty_n.read())) && 
         esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_1))) {
        result_V_we0 = ap_const_logic_1;
    } else {
        result_V_we0 = ap_const_logic_0;
    }
}

void i2_proc::thread_ret_V_8_fu_632_p2() {
    ret_V_8_fu_632_p2 = (!mul_ln1371_reg_722.read().is_01() || !zext_ln215_fu_628_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(mul_ln1371_reg_722.read()) + sc_biguint<18>(zext_ln215_fu_628_p1.read()));
}

void i2_proc::thread_ret_V_fu_623_p2() {
    ret_V_fu_623_p2 = (!shl_ln_fu_615_p3.read().is_01() || !zext_ln81_reg_817.read().is_01())? sc_lv<14>(): (sc_biguint<14>(shl_ln_fu_615_p3.read()) + sc_biguint<14>(zext_ln81_reg_817.read()));
}

void i2_proc::thread_select_ln887_fu_556_p3() {
    select_ln887_fu_556_p3 = (!p_Result_5_fu_549_p3.read()[0].is_01())? sc_lv<14>(): ((p_Result_5_fu_549_p3.read()[0].to_bool())? ap_const_lv14_3FFF: ap_const_lv14_0);
}

void i2_proc::thread_sext_ln821_fu_637_p1() {
    sext_ln821_fu_637_p1 = esl_sext<64,13>(add_ln821_reg_830.read());
}

void i2_proc::thread_shl_ln821_fu_658_p2() {
    shl_ln821_fu_658_p2 = (!zext_ln821_8_fu_655_p1.read().is_01())? sc_lv<8>(): ap_const_lv8_FF << (unsigned short)zext_ln821_8_fu_655_p1.read().to_uint();
}

void i2_proc::thread_shl_ln_fu_615_p3() {
    shl_ln_fu_615_p3 = esl_concat<8,6>(p_0982_0_i_i_reg_371.read(), ap_const_lv6_0);
}

void i2_proc::thread_sum1_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        sum1_V_address0 =  (sc_lv<8>) (zext_ln544_26_fu_590_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        sum1_V_address0 =  (sc_lv<8>) (zext_ln544_24_reg_807.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sum1_V_address0 =  (sc_lv<8>) (zext_ln544_25_reg_784.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sum1_V_address0 =  (sc_lv<8>) (zext_ln544_23_fu_480_p1.read());
    } else {
        sum1_V_address0 = "XXXXXXXX";
    }
}

void i2_proc::thread_sum1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        sum1_V_ce0 = ap_const_logic_1;
    } else {
        sum1_V_ce0 = ap_const_logic_0;
    }
}

void i2_proc::thread_sum1_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        sum1_V_d0 = icmp_ln887_34_fu_571_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sum1_V_d0 = icmp_ln887_35_fu_564_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sum1_V_d0 = ap_const_lv1_0;
    } else {
        sum1_V_d0 =  (sc_lv<1>) ("X");
    }
}

void i2_proc::thread_sum1_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_30_fu_468_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        sum1_V_we0 = ap_const_logic_1;
    } else {
        sum1_V_we0 = ap_const_logic_0;
    }
}

void i2_proc::thread_sum_V_fu_462_p2() {
    sum_V_fu_462_p2 = (!zext_ln68_fu_458_p1.read().is_01() || !p_0757_4_i_i_reg_315.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln68_fu_458_p1.read()) + sc_biguint<13>(p_0757_4_i_i_reg_315.read()));
}

void i2_proc::thread_tmp_35_fu_511_p3() {
    tmp_35_fu_511_p3 = esl_concat<12,8>(tmp_fu_502_p4.read(), p_0856_0_i_i_reg_349.read());
}

void i2_proc::thread_tmp_fu_502_p4() {
    tmp_fu_502_p4 = mul_ln791_reg_703.read().range(19, 8);
}

void i2_proc::thread_x6_V_fu_474_p2() {
    x6_V_fu_474_p2 = (!p_0734_0_i_i_reg_338.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(p_0734_0_i_i_reg_338.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void i2_proc::thread_x7_V_fu_491_p2() {
    x7_V_fu_491_p2 = (!p_0856_0_i_i_reg_349.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(p_0856_0_i_i_reg_349.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void i2_proc::thread_x8_V_fu_530_p2() {
    x8_V_fu_530_p2 = (!p_0895_0_i_i_reg_360.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(p_0895_0_i_i_reg_360.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void i2_proc::thread_y3_V_fu_429_p2() {
    y3_V_fu_429_p2 = (!p_0688_0_i_i_reg_304.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(p_0688_0_i_i_reg_304.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void i2_proc::thread_zext_ln180_1_fu_665_p1() {
    zext_ln180_1_fu_665_p1 = esl_zext<64,18>(ret_V_8_reg_845.read());
}

void i2_proc::thread_zext_ln215_fu_628_p1() {
    zext_ln215_fu_628_p1 = esl_zext<18,14>(ret_V_fu_623_p2.read());
}

void i2_proc::thread_zext_ln544_22_fu_435_p1() {
    zext_ln544_22_fu_435_p1 = esl_zext<64,8>(p_0688_0_i_i_reg_304.read());
}

void i2_proc::thread_zext_ln544_23_fu_480_p1() {
    zext_ln544_23_fu_480_p1 = esl_zext<64,8>(p_0734_0_i_i_reg_338.read());
}

void i2_proc::thread_zext_ln544_24_fu_536_p1() {
    zext_ln544_24_fu_536_p1 = esl_zext<64,8>(p_0895_0_i_i_reg_360.read());
}

void i2_proc::thread_zext_ln544_25_fu_497_p1() {
    zext_ln544_25_fu_497_p1 = esl_zext<64,8>(p_0856_0_i_i_reg_349.read());
}

void i2_proc::thread_zext_ln544_26_fu_590_p1() {
    zext_ln544_26_fu_590_p1 = esl_zext<64,8>(p_0982_0_i_i_reg_371.read());
}

void i2_proc::thread_zext_ln544_fu_382_p1() {
    zext_ln544_fu_382_p1 = esl_zext<64,5>(p_0510_0_dout.read());
}

void i2_proc::thread_zext_ln68_fu_458_p1() {
    zext_ln68_fu_458_p1 = esl_zext<13,1>(p_Result_s_fu_451_p3.read());
}

void i2_proc::thread_zext_ln786_fu_545_p1() {
    zext_ln786_fu_545_p1 = esl_zext<14,13>(result_V_q0.read());
}

void i2_proc::thread_zext_ln791_4_fu_519_p1() {
    zext_ln791_4_fu_519_p1 = esl_zext<64,20>(tmp_35_fu_511_p3.read());
}

void i2_proc::thread_zext_ln81_fu_541_p1() {
    zext_ln81_fu_541_p1 = esl_zext<14,7>(bvh_d_index_reg_292.read());
}

void i2_proc::thread_zext_ln821_8_fu_655_p1() {
    zext_ln821_8_fu_655_p1 = esl_zext<8,4>(tmp_37_reg_840.read());
}

void i2_proc::thread_zext_ln821_fu_596_p1() {
    zext_ln821_fu_596_p1 = esl_zext<13,8>(p_0982_0_i_i_reg_371.read());
}

void i2_proc::thread_zext_ln887_fu_407_p1() {
    zext_ln887_fu_407_p1 = esl_zext<32,7>(bvh_d_index_reg_292.read());
}

void i2_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_0510_0_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_fu_411_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln887_29_fu_423_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && !(esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, match2_empty_n.read())) && esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(icmp_ln887_31_fu_439_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, match2_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_30_fu_468_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && ((esl_seteq<1,1,1>(compute2_V1_load_reg_713.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_32_fu_524_p2.read())) || 
  (esl_seteq<1,1,1>(ap_const_lv1_0, compute2_V1_load_reg_713.read()) && 
   esl_seteq<1,1,1>(icmp_ln887_33_fu_485_p2.read(), ap_const_lv1_1))))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(compute2_V1_load_reg_713.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln887_32_fu_524_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln887_36_fu_578_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

