#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("hcl_rdv3_V_address0", 18, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("hcl_rdv3_V_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("hcl_rdv3_V_q0", 64, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("hcl_trainLabels_V_address0", 13, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("hcl_trainLabels_V_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("hcl_trainLabels_V_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("hcl_in_train_V_address0", 20, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("hcl_in_train_V_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("hcl_in_train_V_q0", 64, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("hcl_in_test_V_address0", 18, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("hcl_in_test_V_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("hcl_in_test_V_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("hcl_testLabels_V_address0", 11, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("hcl_testLabels_V_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("hcl_testLabels_V_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("hcl_testLabels_V_d0", 32, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("hcl_testLabels_V_q0", 32, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("hcl_testLabels_V_address1", 11, hls_out, 4, "ap_memory", "MemPortADDR2", 1),
	Port_Property("hcl_testLabels_V_ce1", 1, hls_out, 4, "ap_memory", "MemPortCE2", 1),
	Port_Property("hcl_testLabels_V_we1", 1, hls_out, 4, "ap_memory", "MemPortWE2", 1),
	Port_Property("hcl_testLabels_V_d1", 32, hls_out, 4, "ap_memory", "MemPortDIN2", 1),
	Port_Property("hcl_testLabels_V_q1", 32, hls_in, 4, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("hcl_epoch_V", 32, hls_in, 5, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "test";
